//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "EmoticonCustomManageAddLogicDelegate.h"
#import "IAPPEmoticonDownloadExt.h"
#import "MMUIViewControllerDelegate.h"

@class EmoticonCustomManageAddLogic, MMEmoticonView, NSString, SightIconView, UIImageView;

@interface AppEmoticonMessageNodeView : BaseMessageNodeView <EmoticonCustomManageAddLogicDelegate, MMUIViewControllerDelegate, IAPPEmoticonDownloadExt>
{
    UIImageView *m_bottomInfoBkgView;
    SightIconView *m_sightIconView;
    MMEmoticonView *m_oImageView;
    EmoticonCustomManageAddLogic *_addEmoticonLogic;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)SaveEmoticon:(id)arg1;
- (_Bool)StartDownload;
@property(retain, nonatomic) EmoticonCustomManageAddLogic *addEmoticonLogic; // @synthesize addEmoticonLogic=_addEmoticonLogic;
- (void)dealloc;
- (id)getMoreMainInfomationAccessibilityDescription;
- (id)getViewController;
- (id)initWithMessageWrap:(id)arg1 Contact:(id)arg2 ChatContact:(id)arg3;
- (_Bool)isDownloaded;
- (_Bool)isDownloading;
- (void)layoutSubviewsInternal;
@property(retain, nonatomic) MMEmoticonView *m_oImageView; // @synthesize m_oImageView;
- (void)onAppEmoticonDownloadFinished:(id)arg1;
- (void)onAppEmoticonDownloading:(id)arg1;
- (void)onClearResource;
- (void)onClick;
- (void)onDisappear;
- (void)onForward:(id)arg1;
- (void)onLongTouch;
- (void)onMenuItemWillHide;
- (void)onMoreOperate:(id)arg1;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchUpInside;
- (void)showOperations;
- (void)showSightIconWithIconType:(int)arg1;
- (void)showbottomInfoBkgView;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)updateEmoticonView;
- (void)updateNodeStatus:(id)arg1;
- (void)updateStatus:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

