//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ImageMessageNodeView.h"

@interface AppImageMessageNodeView : ImageMessageNodeView
{
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (id)getMaskedMsgImgThumb:(id)arg1;
- (id)getMoreMainInfomationAccessibilityDescription;
- (id)hdImagePath;
- (_Bool)ifAppInfoAreaInContent;
- (id)maskedThumbImagePath;
- (void)onCopy:(id)arg1;
- (void)onForward:(id)arg1;
- (void)showImage;
- (id)thumbImage;
- (id)thumbImagePath;

@end

