//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "MMWebImageViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class NSString, UIImageView, UILabel;

@interface AppUrlMessageNodeView : BaseMessageNodeView <MMWebImageViewDelegate, UIAlertViewDelegate>
{
    UILabel *m_detailLabel;
    UILabel *m_titleLabel;
    UIImageView *m_thumbImageView;
    UIImageView *m_oBlurBkgImageView;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)addFavorite;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)canPeek;
- (void)clickNodeViewBtn:(id)arg1;
- (id)getBackgroundImage;
- (id)getDefaultThumbImage;
- (id)getDescText;
- (id)getHostStr;
- (id)getMoreMainInfomationAccessibilityDescription;
- (id)getThumbView:(id)arg1 LocalID:(unsigned int)arg2;
- (id)getTitleLabel;
- (id)getTitleText;
- (void)initDetailLabel;
- (void)initUIInternal;
- (void)initVideoIcon;
- (void)layoutCommonSubViewInternal;
- (void)layoutSubviewsInternal;
@property(readonly, nonatomic) UIImageView *m_thumbImageView; // @synthesize m_thumbImageView;
- (void)onAppear;
- (void)onClearResource;
- (void)onClick;
- (void)onDisappear;
- (void)onFavoriteAdd:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onLoadImageOK:(id)arg1;
- (void)onLongTouch;
- (void)onMenuItemWillHide;
- (void)onMoreOperate:(id)arg1;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchUpInside;
- (void)resend;
- (void)showOpearation;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)updateBkgImage:(_Bool)arg1;
- (void)updateStatus:(id)arg1;
- (void)updateThumbImage;
- (id)viewControllerToPreviewWithFromController:(id)arg1 forLocation:(struct CGPoint)arg2 inCoordinateView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

