//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ReaderNewMessageNodeView.h"

@class CTRichTextView;

@interface AttributedReaderMessageNodeaView : ReaderNewMessageNodeView
{
    CTRichTextView *m_ctRichTextView;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)ShowReader:(id)arg1;
- (double)attributedNodeItemWidth;
- (void)clickNodeViewBtn:(id)arg1;
- (void)forwardMessage;
- (id)getAsyncImageWithFrame:(struct CGRect)arg1;
- (id)getBigVideoImage;
- (id)getItemDesc:(double)arg1 forReaderWrap:(id)arg2;
- (id)getItemLabel:(id)arg1 with:(double)arg2 size:(double)arg3;
- (id)getItemTitle:(double)arg1;
- (id)getSmallVideoImage;
- (id)getTitleString:(id)arg1 bBig:(_Bool)arg2 bGray:(_Bool)arg3;
- (_Bool)isTouchInView:(id)arg1;
- (void)layoutSubviewsInternal;
- (void)onClearResource;
- (void)onClicked;
- (void)onDisappear;
- (void)onFavoriteAdd:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onLongTouch;
- (void)onMenuItemWillHide;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchUpInside;
- (void)reLayoutSubviews;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)updateBkgImage:(_Bool)arg1;
- (void)updateStatus:(id)arg1;

@end

