//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class BakChatUploadPackageHelperStruct, NSDate, NSMutableArray;

@interface BakChatUploadBreakPointStruct : NSObject <NSCoding>
{
    BakChatUploadPackageHelperStruct *m_bakChatUploadpackageHelperStruct;
    unsigned int totalCount;
    unsigned int count;
    NSDate *startDate;
    NSMutableArray *m_packageArray;
    NSMutableArray *m_uploadingPackageArray;
    int m_bakChatUploadStatus;
}

+ (id)recoverBreakPointStruct;
+ (_Bool)removeUploadBreakPointStruct;
+ (_Bool)saveUploadBreakPointStruct:(id)arg1;
- (void).cxx_destruct;
- (void)clear;
@property(nonatomic) unsigned int count; // @synthesize count;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) int m_bakChatUploadStatus; // @synthesize m_bakChatUploadStatus;
@property(retain, nonatomic) BakChatUploadPackageHelperStruct *m_bakChatUploadpackageHelperStruct; // @synthesize m_bakChatUploadpackageHelperStruct;
@property(retain, nonatomic) NSMutableArray *m_packageArray; // @synthesize m_packageArray;
@property(retain, nonatomic) NSMutableArray *m_uploadingPackageArray; // @synthesize m_uploadingPackageArray;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate;
@property(nonatomic) unsigned int totalCount; // @synthesize totalCount;

@end

