//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ChatMigrationCreateQRCodeDelegate.h"
#import "ChatMigrationServerDataProcessMgrDelegate.h"
#import "LocalAreaNetworkServerDelegate.h"

@class ChatMigrationCreateQRCode, ChatMigrationServerDataProcessMgr, LocalAreaNetworkServer, MMTimer, NSData, NSString;

@interface ChatMigrationServerLogic : MMObject <LocalAreaNetworkServerDelegate, ChatMigrationCreateQRCodeDelegate, ChatMigrationServerDataProcessMgrDelegate>
{
    ChatMigrationServerDataProcessMgr *m_DataProcMgr;
    LocalAreaNetworkServer *m_NetworkHandle;
    ChatMigrationCreateQRCode *m_GetQRCodeHandle;
    NSString *server_ip;
    unsigned short server_port;
    NSString *pcName;
    NSString *pcAcctName;
    NSData *offlineAESKey;
    NSString *offlineTicket;
    NSString *offlineResponseHello;
    NSString *offlineResponseOk;
    unsigned int uiCryptUin;
    MMTimer *m_transferSpeedTimer;
    id <ChatMigrationServerLogicDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)GetQRCodeImg;
- (void)GetQRCodeImgOffline;
- (id)GetServerIP;
- (unsigned short)GetServerPort;
- (void)checkTransferSpeed;
- (void)clearTempData;
- (void)dealloc;
- (id)init;
- (id)initWithSessionArray:(id)arg1;
- (_Bool)isClientSupportResumeFromBreakPoint;
- (_Bool)isServerSupportCreateQRCodeOffline;
@property(nonatomic) __weak id <ChatMigrationServerLogicDelegate> m_delegate; // @synthesize m_delegate;
- (void)onConnected;
- (void)onDisconnect;
- (void)onGetQRCode:(id)arg1;
- (void)onGetQRCodeOffline:(id)arg1;
- (void)onNotifyEvent:(int)arg1;
- (void)onProcError:(int)arg1;
- (void)onReciveData:(id)arg1 andLength:(unsigned int)arg2;
- (void)onSendData:(id)arg1;
- (void)onSizeNoGrow;
- (void)onTransferProgress:(unsigned int)arg1 procSize:(unsigned int)arg2;
- (_Bool)startServerService;
- (void)stopServerService;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

