//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "CNetworkStatusExt.h"
#import "ChatMigrationClientLogicDelegate.h"
#import "ChatMigrationRecoverNotificationExt.h"
#import "ILinkEventExt.h"
#import "IdleTimerUtilExt.h"
#import "UIAlertViewDelegate.h"

@class ChatMigrationClientLogic, NSString, UIButton, UIImageView, UIScrollView, UITextField, UIView;

@interface ChatMigrationClientViewController : MMUIViewController <UIAlertViewDelegate, ChatMigrationClientLogicDelegate, ChatMigrationRecoverNotificationExt, ILinkEventExt, IdleTimerUtilExt, CNetworkStatusExt>
{
    id kickOutLogicObj;
    SEL kickOutSel;
    ChatMigrationClientLogic *m_CMClientLogic;
    UIScrollView *m_ScollView;
    UIView *m_IconView;
    UIView *m_EnvCheckHeaderView;
    UIView *m_EnvCheckFooterView;
    UIView *m_ConfirmHeaderView;
    UIView *m_ConfirmFooterView;
    UIView *m_TransferHeaderView;
    UIView *m_TransferFooterView;
    UIView *m_RecoverHeaderView;
    UIView *m_RecoverFooterView;
    UIImageView *m_ServerIPBackView;
    UIImageView *m_ServerPortBackView;
    UITextField *m_ServerIPTextField;
    UITextField *m_ServerPortTextField;
    UIButton *m_ConnectServerBtn;
    _Bool bIsExitView;
    _Bool bIsCreatedFirstStage;
    _Bool bIsStartedRecover;
    unsigned int uiSurplusSize;
    unsigned int uiCurSpeed;
    int iStep;
    int iTransferErrorCode;
    _Bool isFirstCreateRD;
    _Bool isFirstCreateRF;
    _Bool isFirstCreateRC;
    _Bool bIsUseHotPot;
    unsigned int uiTotalSize;
    unsigned int uiTransferSize;
    NSString *serverIP;
    _Bool isShowDisconnect;
    double m_transferStartTime;
    double m_transferTotalTime;
    _Bool m_hasTransferStart;
    NSString *backupUrl;
}

- (void).cxx_destruct;
- (void)DidEnterBackground:(id)arg1;
- (void)ReachabilityChange:(unsigned int)arg1;
- (void)RealDismissMyself;
- (void)addConfirmBtnAtFooterView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSString *backupUrl; // @synthesize backupUrl;
- (int)checkMigrationCondition;
- (void)dealWithDisconnetOrNetworkChange;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)getBackupURLFromRescanQRCode:(id)arg1;
- (double)getContentViewY;
- (id)init;
- (void)initDebugStage;
- (_Bool)isLogout;
- (void)makeEnvironmentCheckStageWithRedTips:(id)arg1 withGreyTips:(id)arg2 withHelpString:(id)arg3;
- (void)makeFirstStage;
- (void)makeGateWayErrorIconView;
- (void)makeIconView;
- (void)makeRecoverStage;
- (void)makeRescanPage;
- (void)makeScrollView;
- (void)makeTransferStage;
- (void)onBackBtnDone:(id)arg1;
- (void)onCleanTmpFile;
- (void)onConnectBtnDone:(id)arg1;
- (void)onDBRecoverProgress:(unsigned int)arg1 andFinishCount:(unsigned int)arg2;
- (void)onDisconnect;
- (void)onGetConnectInfo:(id)arg1 andPort:(unsigned short)arg2;
- (void)onGetConnectInfoError;
- (void)onGetConnectInfoNotSameAccount:(id)arg1;
- (void)onIdleTimerUtilVoipQuit;
- (void)onInspectLocalConditionFail:(int)arg1;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onMediaFileRecoverProgress:(unsigned int)arg1 andFinishCount:(unsigned int)arg2;
- (void)onRecoverChatFailure;
- (void)onRecoverChatSuccess;
- (void)onRecoverStart;
- (void)onRecvStartResponse;
- (void)onSetHotSpot:(id)arg1;
- (void)onShowDebugReportViewController;
- (void)onShowGetConnectInfoError;
- (void)onSimCardNetTypeChange;
- (void)onTransferError:(int)arg1;
- (void)onTransferFinish;
- (void)onTransferProgress:(unsigned int)arg1 processedSize:(unsigned int)arg2;
- (void)onTransferSpeed:(float)arg1;
- (void)reScanQRCode;
- (void)registerKickOutEvent:(id)arg1 sel:(SEL)arg2;
- (void)relayoutEnviromentCheckView;
- (void)reportKVStat;
- (void)showDisconnect;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

