//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "CNetworkStatusExt.h"
#import "ILinkEventExt.h"

@class CTRichTextView, MMLoadingView, NSString, UIButton, UILabel, UIScrollView, UIView;

@interface ChatMigrationMainViewController : MMUIViewController <CNetworkStatusExt, ILinkEventExt>
{
    _Bool bNetWorkStateOk;
    _Bool bEnoughBatteryLevel;
    _Bool bEnoughDiskSpace;
    unsigned long long m_MoreDiskSpace;
    UIView *m_IconView;
    UIScrollView *m_ScrollView;
    UILabel *m_tipsLabel;
    UILabel *m_statusLabel;
    UIButton *m_actionButton;
    MMLoadingView *m_loadingView;
    _Bool m_bShowBackupButton;
    CTRichTextView *m_backupButton;
    UIButton *m_backupButtonTmp;
    _Bool m_bUseTmpButton;
}

- (void).cxx_destruct;
- (void)ReachabilityChange:(unsigned int)arg1;
- (void)cleanCache;
- (void)dealloc;
- (void)doCleanCache;
- (id)init;
- (void)initLoadingView;
- (void)makeIconView;
- (void)makeMainView;
- (void)makeMainViewWithShowDiskWarning:(_Bool)arg1;
- (void)makeScrollView;
- (void)onActionButtonPress;
- (void)onBackBtnDone:(id)arg1;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onShowBackupWebView;
- (void)onShowSelectSessionViewController;
- (void)onSimCardNetTypeChange;
- (void)startLoadSessionData;
- (void)startLoading;
- (void)stateDetect;
- (void)stopLoading;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

