//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMTableViewInfoDelegate.h"

@class CBaseContact, MMTableViewInfo, NSCalendar, NSDate, NSDateComponents, NSString, UIButton, UIImage;

@interface ChatMsgCalendarViewController : MMUIViewController <MMTableViewInfoDelegate>
{
    CBaseContact *m_oContact;
    MMTableViewInfo *m_tableViewInfo;
    NSCalendar *m_gregorian;
    NSCalendar *m_chinese;
    UIImage *m_backImg;
    UIImage *m_normalImg;
    NSDate *m_lastDatePreMonth;
    NSDateComponents *m_lastMsgDateComponents;
    _Bool m_bEnd;
    UIButton *m_lastSelectItem;
    _Bool m_bToday;
    _Bool m_bNewYearsEve;
}

- (void).cxx_destruct;
- (id)getDetailForDay:(long long)arg1 Month:(long long)arg2 Year:(long long)arg3;
- (void)getNextDateComponents;
- (_Bool)hasMsgDay:(long long)arg1 Month:(long long)arg2 Year:(long long)arg3;
- (id)initWithChat:(id)arg1;
- (void)makeMonthlyViewWithDate:(id)arg1;
- (void)makeWeekView;
- (void)makeWeeklyLineCell:(id)arg1 CellInfo:(id)arg2;
- (id)makeWeeklyLineView:(long long *)arg1 WeekDay:(long long)arg2 thisMonthComponent:(id)arg3;
- (void)onBackButtonClicked:(id)arg1;
- (void)onSelectDate:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)shouldLoadNextMonth;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

