//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "WCActionSheetDelegate.h"

@class GoogleContact, MMAnimationTipView, NSString, UIButton;

@interface ContactsGoogleNoWeChatViewController : MMUIViewController <WCActionSheetDelegate>
{
    GoogleContact *m_googleContact;
    MMAnimationTipView *m_tipView;
    UIButton *m_inviteButton;
    id <GoogleContactViewDelegate> m_googleContactViewDelegate;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)init;
- (void)initDetailInfoView;
- (id)initWithContact:(id)arg1;
@property(retain, nonatomic) GoogleContact *m_googleContact; // @synthesize m_googleContact;
@property(nonatomic) __weak id <GoogleContactViewDelegate> m_googleContactViewDelegate; // @synthesize m_googleContactViewDelegate;
@property(retain, nonatomic) UIButton *m_inviteButton; // @synthesize m_inviteButton;
@property(retain, nonatomic) MMAnimationTipView *m_tipView; // @synthesize m_tipView;
- (void)onInvite:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

