//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DeviceInfo : NSObject
{
}

+ (id)DBus;
+ (id)DCPU;
+ (id)DCache;
+ (id)DMemory;
+ (id)DModel;
+ (id)DSystem;
+ (double)FreeDiskSpaceSize;
+ (double)TotalDiskSpaceSize;
+ (id)bssid;
+ (id)deviceXml;
+ (_Bool)hasForceTouchCapability:(id)arg1;
+ (_Bool)is480hScreen;
+ (_Bool)is568hScreen;
+ (_Bool)is667hScreen;
+ (_Bool)is736hScreen;
+ (_Bool)isLowPerformanceDevice;
+ (_Bool)isSupportSplitView;
+ (_Bool)isUnderiPhone4s;
+ (_Bool)isUnderiPhone6;
+ (_Bool)isiOS10plus;
+ (_Bool)isiOS7;
+ (_Bool)isiOS7_1plus;
+ (_Bool)isiOS7plus;
+ (_Bool)isiOS8_1;
+ (_Bool)isiOS8_1plus;
+ (_Bool)isiOS8_2plus;
+ (_Bool)isiOS8_3plus;
+ (_Bool)isiOS8_4plus;
+ (_Bool)isiOS8plus;
+ (_Bool)isiOS9_1plus;
+ (_Bool)isiOS9plus;
+ (_Bool)isiPad;
+ (_Bool)isiPad1;
+ (_Bool)isiPad2;
+ (_Bool)isiPad3;
+ (_Bool)isiPad4;
+ (_Bool)isiPadAir;
+ (_Bool)isiPadAir2;
+ (_Bool)isiPadMini;
+ (_Bool)isiPadPro;
+ (_Bool)isiPadUniversal;
+ (_Bool)isiPhone;
+ (_Bool)isiPhone2G;
+ (_Bool)isiPhone3G;
+ (_Bool)isiPhone3GS;
+ (_Bool)isiPhone4;
+ (_Bool)isiPhone4S;
+ (_Bool)isiPhone5;
+ (_Bool)isiPhone5C;
+ (_Bool)isiPhone5S;
+ (_Bool)isiPhone6;
+ (_Bool)isiPhone6Screen;
+ (_Bool)isiPhone6p;
+ (_Bool)isiPhone6pScreen;
+ (_Bool)isiPhone6s;
+ (_Bool)isiPhone6sp;
+ (_Bool)isiPodTouch;
+ (_Bool)isiPodTouch1;
+ (_Bool)isiPodTouch2;
+ (_Bool)isiPodTouch3;
+ (_Bool)isiPodTouch4;
+ (_Bool)isiPodTouch5;
+ (id)modelPlatform;

@end

