//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableDictionary, NSString;

@interface EmoticonWebDownloadMgr : MMService <MMService>
{
    NSMutableDictionary *m_downloadQueue;
}

- (void).cxx_destruct;
- (id)cachePathForUrl:(id)arg1;
- (id)cacheRootPath;
- (_Bool)cancelDownloadEmoticon:(id)arg1 ThumbUrl:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)dealloc;
- (_Bool)downloadEmoticon:(id)arg1 withUserData:(id)arg2;
- (id)downloadTempPathForUrl:(id)arg1;
- (id)hashForUrl:(id)arg1;
- (id)infoForUrlConnnection:(id)arg1;
- (id)init;
- (_Bool)isEmoticonExist:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *m_downloadQueue; // @synthesize m_downloadQueue;
- (void)onServiceInit;
- (id)thumbForImageData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

