//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface EmoticonMd5Object : MMObject <PBCoding>
{
    unsigned int m_status;
    NSString *m_md5;
    NSString *m_cdnUrl;
    NSString *m_designerId;
    NSString *m_thumbImgUrl;
    NSString *m_encryptUrl;
    NSString *m_aesKey;
    NSString *m_productId;
}

+ (unsigned int)StatusValueComplete;
+ (unsigned int)StatusValueFailed;
+ (unsigned int)StatusValueUnComplete;
+ (void)initialize;
- (void).cxx_destruct;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (id)init;
@property(retain, nonatomic) NSString *m_aesKey; // @synthesize m_aesKey;
@property(retain, nonatomic) NSString *m_cdnUrl; // @synthesize m_cdnUrl;
@property(retain, nonatomic) NSString *m_designerId; // @synthesize m_designerId;
@property(retain, nonatomic) NSString *m_encryptUrl; // @synthesize m_encryptUrl;
@property(retain, nonatomic) NSString *m_md5; // @synthesize m_md5;
@property(retain, nonatomic) NSString *m_productId; // @synthesize m_productId;
@property(nonatomic) unsigned int m_status; // @synthesize m_status;
@property(retain, nonatomic) NSString *m_thumbImgUrl; // @synthesize m_thumbImgUrl;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

