//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSMutableArray;

@interface EmoticonBackupMd5ListCgi : MMObject <PBMessageObserverDelegate>
{
    _Bool m_hasStartRequestOnce;
    _Bool m_ignoreLimit;
    unsigned int m_eventId;
    id <EmoticonBackupMd5ListCgiDelegate> m_delegate;
    NSMutableArray *m_md5List;
    NSMutableArray *m_needUploadMd5List;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)callFailedDelegate;
- (void)callNoNeedToBackupDelegate;
- (void)callOkDelegate;
- (void)dealloc;
- (id)initWithMd5List:(id)arg1 delegate:(id)arg2;
- (void)internalRequest;
- (_Bool)isActive;
@property(nonatomic) __weak id <EmoticonBackupMd5ListCgiDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) unsigned int m_eventId; // @synthesize m_eventId;
@property(nonatomic) _Bool m_hasStartRequestOnce; // @synthesize m_hasStartRequestOnce;
@property(nonatomic) _Bool m_ignoreLimit; // @synthesize m_ignoreLimit;
@property(retain, nonatomic) NSMutableArray *m_md5List; // @synthesize m_md5List;
@property(retain, nonatomic) NSMutableArray *m_needUploadMd5List; // @synthesize m_needUploadMd5List;
- (void)startRequest;

@end

