//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface EmoticonCustomReportData : MMObject
{
}

+ (void)ReportAutoStartSync;
+ (void)ReportConfirmStartSyncAtCellNetwork;
+ (void)ReportCustomEmoticonCountWhenStartRecover:(unsigned long long)arg1;
+ (void)ReportCustomEmoticonManageIconClick;
+ (void)ReportCustomEmoticonStoreEntranceClick;
+ (void)ReportCustomEmoticonStoreTabClick;
+ (void)ReportCustomEmoticonTabClick;
+ (void)ReportDesignerEmojiClickTagEntrance;
+ (void)ReportDesignerEmojiTipsClickAddEmoticonWithScene:(unsigned int)arg1 Md5:(id)arg2;
+ (void)ReportDesignerEmojiTipsClickSendEmoticonWithScene:(unsigned int)arg1 Md5:(id)arg2;
+ (void)ReportDesignerEmojiTipsShowTipsWithScene:(unsigned int)arg1 Md5:(id)arg2;
+ (void)ReportEmoticonCustomManageAddClick;
+ (void)ReportEmoticonCustomManageEditClick;
+ (void)ReportEmoticonCustomManageEnterFromCell;
+ (void)ReportEmoticonCustomManageEnterFromOverLimitTips;
+ (void)ReportEmoticonFreeClick;
+ (void)ReportEmoticonNewClick;
+ (void)ReportEmoticonTabEntranceClick;
+ (void)ReportHasEmoticonToSync;
+ (void)ReportManualStartSyncAtCellNetwork;
+ (void)ReportManualStopSync;

@end

