//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMBaseSessionInfo.h"

#import "WCDBCoding.h"

@class NSString;

@interface EnterpriseSessionInfo : MMBaseSessionInfo <WCDBCoding>
{
    unsigned int atMeCount;
    unsigned int newUnreadCount;
    unsigned int newAtMeCount;
    unsigned int lastExposeTime;
    unsigned int chatType;
    unsigned int sessionTopTime;
    long long m___rowID;
    NSString *_brandUserName;
}

+ (id)dummyObject;
+ (const map_0e718273 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_0e718273 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_7a576766 *)getValueNameIndexMap;
+ (id)getValueTable;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (id)sessionInfoWithContact:(id)arg1 lastMessage:(id)arg2 Brand:(id)arg3;
- (void).cxx_destruct;
- (unsigned int)GetUnReadCount:(id)arg1;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(nonatomic) unsigned int atMeCount; // @synthesize atMeCount;
@property(retain, nonatomic) NSString *brandUserName; // @synthesize brandUserName=_brandUserName;
@property(nonatomic) unsigned int chatType; // @synthesize chatType;
- (void)checkExposeTime:(unsigned int)arg1;
- (void)clearAtMeCount;
- (void)clearNewAtMeCount;
- (void)clearNewUnreadCount;
- (id)contact;
- (const WCDBCondition_c6db074e *)db_atMeCount;
- (const WCDBCondition_22fabacd *)db_draftMsg;
- (const WCDBCondition_c6db074e *)db_draftMsgTime;
- (const WCDBCondition_c6db074e *)db_lastExposeTime;
- (const WCDBCondition_c6db074e *)db_lastMsgUpdateTime;
- (const WCDBCondition_c6db074e *)db_newAtMeCount;
- (const WCDBCondition_c6db074e *)db_newUnreadCount;
- (const WCDBCondition_c6db074e *)db_sessionFlag;
- (const WCDBCondition_22fabacd *)db_sessionId;
- (const WCDBCondition_c6db074e *)db_sessionTopTime;
- (const WCDBCondition_c6db074e *)db_unreadCount;
- (void)fixCount;
- (id)genContact;
- (id)genLastMessage;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (void)incAtMeCount;
- (void)incNewAtMeCount;
- (id)initWithContact:(id)arg1 lastMessage:(id)arg2 Brand:(id)arg3;
- (_Bool)isSessionTop;
@property(nonatomic) unsigned int lastExposeTime; // @synthesize lastExposeTime;
- (id)lastMessage;
@property(nonatomic) unsigned int newAtMeCount; // @synthesize newAtMeCount;
@property(nonatomic) unsigned int newUnreadCount; // @synthesize newUnreadCount;
- (unsigned int)sessionTopTime;
- (void)setSessionTopTime:(unsigned int)arg1;
- (void)updateContact;
- (void)updateContactAndDraft;
- (_Bool)updateContactAndTopTime;
- (void)updateExposeTime;
- (void)updateLastMessage;
- (void)updateNewUnreadCount;
- (void)updateUnreadCount;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

