//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class EnterpriseBrandEntryItemViewLayoutParam, MMBadgeView, UIButton, UIImageView, UILabel, UIView;

@interface EnterpriseBrandEntryItemView : MMTableViewCell
{
    EnterpriseBrandEntryItemViewLayoutParam *_layoutParam;
    UIView *_holderView;
    UIImageView *_headImgView;
    UILabel *_titleLabel;
    MMBadgeView *_badgeView;
    UIButton *_rightBtnView;
    id <EnterpriseBrandEntryItemViewDelegate> _delegate;
}

+ (double)cellHeight;
- (void).cxx_destruct;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)layoutSubviews;
- (void)onRightBtnClicked;
- (void)updateWithSpecialBrandSessionCellData:(id)arg1 delegate:(id)arg2;

@end

