//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "FTSDBDelegate.h"
#import "MMDBRRepairerExt.h"
#import "MMKernelExt.h"
#import "MMService.h"

@class AsyncTaskQueueEngine, FTSContactMgr, FTSDB, FTSFavMgr, FTSMemorySearchMgr, FTSMessageMgr, FTSReportMgr, FTSTopHitMgr, FTSWebSearchMgr, MCSBrandContactMgr, NSMutableSet, NSRecursiveLock, NSString, WSMusicMgr;

@interface FTSFacade : MMService <FTSDBDelegate, MMDBRRepairerExt, MMService, MMKernelExt>
{
    FTSDB *_ftsDB;
    AsyncTaskQueueEngine *_asyncTaskQueueEngine;
    _Bool _hasStartAsyncQueue;
    _Bool _isPositioning;
    _Bool _bHasActiveSearch;
    NSRecursiveLock *_lock;
    FTSContactMgr *_ftsContactMgr;
    FTSMessageMgr *_ftsMessageMgr;
    FTSFavMgr *_ftsFavMgr;
    FTSMemorySearchMgr *_ftsMemorySearchMgr;
    FTSWebSearchMgr *_ftsWebSearchMgr;
    WSMusicMgr *_musicMgr;
    FTSReportMgr *_ftsReportMgr;
    NSMutableSet *_imageCacheUrlSet;
    FTSTopHitMgr *_ftsTopHitMgr;
    MCSBrandContactMgr *_mcsBrdContactMgr;
}

- (void).cxx_destruct;
- (void)addImageCacheKey:(id)arg1;
- (void)cancelSearchForHomePage;
- (void)cleanFTSDB;
- (void)clearImageCache;
- (void)dealloc;
- (void)doInitWorker;
- (void)enableForegroundTask;
- (void)forbidForegroundTask;
@property(retain, nonatomic) FTSContactMgr *ftsContactMgr; // @synthesize ftsContactMgr=_ftsContactMgr;
@property(retain, nonatomic) FTSFavMgr *ftsFavMgr; // @synthesize ftsFavMgr=_ftsFavMgr;
@property(retain, nonatomic) FTSMemorySearchMgr *ftsMemorySearchMgr; // @synthesize ftsMemorySearchMgr=_ftsMemorySearchMgr;
@property(retain, nonatomic) FTSMessageMgr *ftsMessageMgr; // @synthesize ftsMessageMgr=_ftsMessageMgr;
@property(retain, nonatomic) FTSReportMgr *ftsReportMgr; // @synthesize ftsReportMgr=_ftsReportMgr;
@property(retain, nonatomic) FTSTopHitMgr *ftsTopHitMgr; // @synthesize ftsTopHitMgr=_ftsTopHitMgr;
@property(retain, nonatomic) FTSWebSearchMgr *ftsWebSearchMgr; // @synthesize ftsWebSearchMgr=_ftsWebSearchMgr;
- (id)init;
- (void)logBeginSearch:(int)arg1;
@property(retain, nonatomic) MCSBrandContactMgr *mcsBrdContactMgr; // @synthesize mcsBrdContactMgr=_mcsBrdContactMgr;
@property(retain, nonatomic) WSMusicMgr *musicMgr; // @synthesize musicMgr=_musicMgr;
- (void)onAuthOK;
- (void)onBeginSearch;
- (void)onEndFtsSearch;
- (void)onEnterBackground;
- (void)onPreHandleRecoverDB;
- (void)onRecoverFTSDB;
- (void)onServiceClearData;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceInit;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceReloadData;
- (void)onServiceTerminate;
- (void)onViewPop;
- (void)reloadDatabase;
- (void)removeImageCacheKey:(id)arg1;
- (void)resetSearchStatus;
- (void)startSearchForHomePage:(id)arg1;
- (void)stopRetrievingLocation;
- (void)updateLocation;
- (void)updateNewestHomePageSearchText:(id)arg1;
- (void)waitAllTask;
- (void)willRepairDB:(unsigned int)arg1 needCatch:(_Bool *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

