//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FTSWebSearchDataSource.h"
#import "INewABTestMgrExt.h"
#import "UIScrollViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UIWebViewDelegate.h"
#import "WSContactSearchLogicDelegate.h"
#import "WSJSEventHandleDelegate.h"
#import "WSTagSearchDelegate.h"

@class MMTagSearchBar, MMUIViewController, NSMutableArray, NSString, UIImageView, UITextField, UIView, WSContactSearchLogic, WSJSEventHandler, WSResultViewLogic, WSTagSearchLogic, WebSearchView;

@interface FTSWebSearchController : NSObject <UISearchBarDelegate, UIWebViewDelegate, UIScrollViewDelegate, FTSWebSearchDataSource, INewABTestMgrExt, WSJSEventHandleDelegate, WSContactSearchLogicDelegate, WSTagSearchDelegate>
{
    MMTagSearchBar *_searchBar;
    WebSearchView *_mainView;
    WebSearchView *_detailView;
    WSResultViewLogic *_resultViewLogic;
    UIImageView *_searchBarWrap;
    UIImageView *_bottomViewShadow;
    _Bool _hasMoving;
    double _moveStartOffset;
    double _moveCurOffset;
    double _moveContentOffsetY;
    double _searchTextFieldNormalWidth;
    struct CGSize _searchIconDefaultSize;
    _Bool _isDetailSearch;
    unsigned long long _detailSearchType;
    NSString *_keywordForHomepage;
    NSString *_keywordForDetailPage;
    NSString *_searchID;
    NSString *_browsingTID;
    NSMutableArray *_arrDeletedTID;
    _Bool _bSwizzle;
    int _guideType;
    int _mode;
    UIView *_view;
    UIView *_searchBarSuperView;
    UIView *_bottomView;
    MMUIViewController *_viewController;
    id <FTSWebSearchViewDelegate> _delegate;
    WSJSEventHandler *_jsEventHandler;
    WSContactSearchLogic *_searchContactLogic;
    WSTagSearchLogic *_tagSearchLogic;
    UITextField *_searchTextField;
    UIImageView *_searchLeftView;
    UIView *_searchPromtLabel;
}

- (void).cxx_destruct;
- (void)asyncSearch:(id)arg1;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
- (unsigned long long)businessType;
- (void)cancelMoveDetailView;
- (void)cancelMoveSearchBar;
- (void)cancelSearch;
- (_Bool)checkBrowsingSnsItem:(id)arg1;
- (void)clearResource;
- (void)currentFriendScene:(unsigned int *)arg1 withParams:(id)arg2;
- (void)dealloc;
@property(nonatomic) __weak id <FTSWebSearchViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)enableButton:(id)arg1;
- (void)enableSearchBar;
- (double)getSearchTextFieldWidth;
- (void)handlePanGesture:(id)arg1;
- (void)handlePanGestureForDetailView:(id)arg1;
- (void)handleRotateEvent;
- (void)hideKeyboard;
- (void)hideSearchKeyboard;
- (id)init;
- (void)initContactSearchLogic;
- (void)initDetailView;
- (void)initResultView;
- (void)initResultViewLogic;
- (void)initTagSearchLogic;
- (void)initView;
- (id)initWithMode:(int)arg1 businessType:(unsigned long long)arg2;
- (void)internalSwizzle;
- (_Bool)isSubClassSearch;
- (_Bool)isSupportLocalSuggestion;
- (_Bool)isSupportMCSBrandContact;
- (_Bool)isSupportSuggestion;
- (_Bool)isVerticalSearch;
@property(retain, nonatomic) WSJSEventHandler *jsEventHandler; // @synthesize jsEventHandler=_jsEventHandler;
- (void)keyboardDidHide:(id)arg1;
- (void)loadLocalHtml:(id)arg1;
- (void)loadLocalHtmlForDetailPage:(id)arg1;
- (void)loadLocalHtmlForVertSearch;
@property(nonatomic) int mode; // @synthesize mode=_mode;
- (void)moveDetailViewToRight;
- (void)moveWebViewToRight;
- (void)notifyPageOfQueryChanged:(id)arg1;
- (void)notifyPageOfSearchClick:(id)arg1;
- (void)onBackBtnClick;
- (void)onBrowsingSnsItem:(id)arg1;
- (void)onClickRecmdWord:(id)arg1;
- (void)onClickSearchButton:(id)arg1;
- (void)onDeleteBrowsingSnsItemOnH5;
- (void)onLaunchDetailPage:(id)arg1;
- (void)onRemoveDetailView;
- (void)onRequestLocalSuggestion:(id)arg1;
- (void)onReturnWSContactResult:(id)arg1;
- (void)onSearchInputChanged:(id)arg1;
- (void)onTagSearchBarInfoChangedToNotify:(id)arg1;
- (void)onWSMusicStatusChanged:(id)arg1;
- (void)pop:(_Bool)arg1;
- (void)popFromDetailSearch;
- (void)popWithAnimation;
- (id)query;
- (void)remove;
- (void)removeAllAnimation:(id)arg1;
- (void)resetSearch;
- (void)resetSearchIconFrame;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (_Bool)searchBar:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
@property(retain, nonatomic) UIView *searchBarSuperView; // @synthesize searchBarSuperView=_searchBarSuperView;
- (void)searchBarTextDidBeginEditing:(id)arg1;
@property(retain, nonatomic) WSContactSearchLogic *searchContactLogic; // @synthesize searchContactLogic=_searchContactLogic;
@property(retain, nonatomic) UIImageView *searchLeftView; // @synthesize searchLeftView=_searchLeftView;
@property(retain, nonatomic) UIView *searchPromtLabel; // @synthesize searchPromtLabel=_searchPromtLabel;
@property(retain, nonatomic) UITextField *searchTextField; // @synthesize searchTextField=_searchTextField;
- (void)setSearchBarText:(id)arg1;
@property(retain, nonatomic) WSTagSearchLogic *tagSearchLogic; // @synthesize tagSearchLogic=_tagSearchLogic;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
@property(nonatomic) __weak MMUIViewController *viewController; // @synthesize viewController=_viewController;
- (void)show;
- (void)swizzle;
- (void)tryAsyncSearchContact:(id)arg1;
- (void)unswizzle;
- (void)updateMovingDetailView;
- (void)updateSearchBarPosition;
- (id)urlParmasForDetailPage:(id)arg1;
- (id)urlParmasForMainPage:(id)arg1;
- (id)urlParmasForVSPage;
- (void)willBeginDetailSearch;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

