//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface GameCenterAppstorePromptView : UIView
{
    UIImageView *_progressingBarView;
}

- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) UIImageView *progressingBarView; // @synthesize progressingBarView=_progressingBarView;
- (void)showAndJumpToAppstore:(id)arg1 AppStoreUrl:(id)arg2 Duration:(double)arg3;

@end

