//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMTimer, NSMutableArray;

@interface GameController : NSObject
{
    NSMutableArray *m_arrNodeData;
    MMTimer *m_timer;
}

+ (void)SetGameContentForMsgWrap:(id)arg1;
+ (id)getMD5ByGameContent:(unsigned int)arg1;
- (void).cxx_destruct;
- (void)Reset;
- (void)addNodeData:(id)arg1;
- (void)dealloc;
- (void)doAnimation;
- (id)init;
@property(retain, nonatomic) MMTimer *m_timer; // @synthesize m_timer;
- (void)sendGameMessage:(id)arg1 toUsr:(id)arg2;
- (void)startTimer;
- (void)stopTimer;

@end

