//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "C2ObjcClientCallBackExt.h"

@class NSDate, NSString, WXGSpeedFilter;

@interface LocalAreaNetworkClient : MMObject <C2ObjcClientCallBackExt>
{
    unsigned long long m_totalReciveLength;
    unsigned long long m_totalSendLength;
    unsigned long long m_lastTotalReciveLength;
    unsigned long long m_lastTotalSendLength;
    NSDate *m_sendStartDate;
    NSDate *m_reciveStartDate;
    WXGSpeedFilter *m_sendSpeedFilter;
    WXGSpeedFilter *m_recveSpeedFilter;
    unsigned short server_port;
    id <LocalAreaNetworkClientDelegate> m_delegate;
    NSString *server_ip;
}

- (void).cxx_destruct;
- (void)Client_Disconnect;
- (unsigned long long)Client_SendData:(id)arg1 andLength:(unsigned int)arg2;
- (float)GetClientRecvSpeed;
- (float)GetClientSendSpeed;
- (void)dealloc;
- (unsigned long long)getClientOpenTime;
- (unsigned long long)getTotalRecvLength;
- (unsigned long long)getTotalSendLength;
- (id)init;
@property(nonatomic) __weak id <LocalAreaNetworkClientDelegate> m_delegate; // @synthesize m_delegate;
- (void)onDisconnect:(id)arg1 port:(unsigned short)arg2;
- (void)onRecv:(id)arg1 port:(unsigned short)arg2 data:(id)arg3 length:(unsigned int)arg4;
- (void)reset;
@property(retain, nonatomic) NSString *server_ip; // @synthesize server_ip;
@property(nonatomic) unsigned short server_port; // @synthesize server_port;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

