//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "GetA8KeyLogicDelegate.h"
#import "IVOIPUILogicMgrExt.h"
#import "SightDistributeTableViewDelegate.h"
#import "SightQRCodeScannerDelegate.h"
#import "UIAlertViewDelegate.h"

@class FrameTextBtn, GetA8KeyLogic, NSString, SightDistributeTableView, SightMomentEditViewController, SightRecordProgressBar, SightView, StrokeView, UIButton, UIImage, UIImageView, UILabel, UIView, UIView<SightPreviewView>, UIViewController;

@interface MainFrameSightViewController : MMUIViewController <IVOIPUILogicMgrExt, UIAlertViewDelegate, SightDistributeTableViewDelegate, SightQRCodeScannerDelegate, GetA8KeyLogicDelegate>
{
    UIImage *m_maskImg;
    UIView *m_contentView;
    UIView *m_backgroundMask;
    UIImageView *m_bottomMask;
    UIImageView *m_topMask;
    UIView *m_cameraPreview;
    UIView<SightPreviewView> *m_cameraView;
    SightRecordProgressBar *m_captureProgress;
    UIButton *m_captureBtn;
    StrokeView *m_btnFrame;
    UILabel *m_btnLabel;
    UIImageView *m_btnIconImg;
    UIImage *m_btnIconImgCancel;
    UIImage *m_btnIconImgNormal;
    UIView *m_qrBar;
    UILabel *m_qrBarLabel;
    NSString *m_qrData;
    GetA8KeyLogic *m_qrLogic;
    _Bool m_isInCamera;
    UIView *m_playerPreview;
    UIView *m_playerContent;
    SightView *_sightView;
    SightDistributeTableView *m_tableView;
    UIView *m_panelNavbarMask;
    FrameTextBtn *m_sendBtn;
    UIView *m_tipsView;
    UILabel *m_tipsLabel;
    UIImageView *m_tipsLabelBG;
    unsigned int m_tipsCounter;
    UIView *m_cancelTips;
    UILabel *m_titleTips;
    UIView *m_motionTipsView;
    _Bool m_motionDetected;
    unsigned int m_currWriterID;
    _Bool m_writerTimeout;
    _Bool m_cameraOK;
    _Bool m_isRecording;
    unsigned int m_compressorID;
    _Bool m_enterMoment;
    SightMomentEditViewController *m_momentController;
    unsigned int m_momentCompressorID;
    _Bool m_clickClose;
    _Bool m_canClose;
    _Bool m_requestAuthAccess;
    _Bool m_lightBoostStat;
    _Bool m_lightBoostOpenStat;
    unsigned int m_validReshowLightBoostCmd;
    unsigned int lightDetectCounter;
    UIButton *m_lightBoostButton;
    UILabel *m_lightBoostHintView;
    _Bool m_hasRealStartedForPreStartRecording;
    _Bool directSentMoment;
    int _recordState;
    int _btnState;
    int _cameraState;
    UIImage *topMask;
    UIImage *bottomMask;
    long long lastBarStyle;
    double _maskAlpha;
    UIViewController *_viewController;
    UIImage *_thumbImg;
    NSString *_videoPath;
    UIImage *_momentThumbImg;
    NSString *_momentVideoPath;
    struct CGPoint _iconCenter;
}

- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) UIImage *bottomMask; // @synthesize bottomMask;
- (void)btnDragInside;
- (void)btnDragOutSide;
- (void)btnDragging:(id)arg1;
- (void)btnPress;
- (void)btnRelease;
@property(nonatomic) int btnState; // @synthesize btnState=_btnState;
@property(nonatomic) int cameraState; // @synthesize cameraState=_cameraState;
@property(readonly, nonatomic) _Bool canClose; // @synthesize canClose=m_canClose;
- (void)cancelWriter;
- (void)checkShakyMovie;
- (void)closeCamera;
- (void)closeLightBoots;
- (void)closeWhenFirstIn;
- (void)closeWithAnim;
- (void)closeWithAnimNotBounce;
- (void)closeWithOutAnim;
- (void)confirmSendMsg;
- (void)dealloc;
@property(nonatomic) _Bool directSentMoment; // @synthesize directSentMoment;
- (void)endFullPlayPreview;
- (void)enterMomentEdit;
- (void)fadeInTips;
- (void)finishWriter;
- (void)focusCenter;
- (void)forceHideTitleTips;
- (void)fullPlayPreview;
- (id)getSubImage:(struct CGRect)arg1 inImage:(id)arg2;
- (void)handleFocusTap:(id)arg1 inView:(id)arg2;
- (void)handlePanBottom:(id)arg1;
- (void)handleZoomTap:(id)arg1;
- (void)hideCancelTips;
- (void)hideTips;
- (void)hideTitleTips;
@property(nonatomic) struct CGPoint iconCenter; // @synthesize iconCenter=_iconCenter;
- (id)init;
- (void)initTipsLabel;
@property(nonatomic) long long lastBarStyle; // @synthesize lastBarStyle;
- (void)lightNormal;
- (void)lightTooLow;
- (void)loadMaskImg;
- (void)logicCheckState:(int)arg1;
- (void)makeMask;
@property(nonatomic) double maskAlpha; // @synthesize maskAlpha=_maskAlpha;
@property(retain, nonatomic) UIImage *maskImg; // @synthesize maskImg=m_maskImg;
@property(retain, nonatomic) UIImage *momentThumbImg; // @synthesize momentThumbImg=_momentThumbImg;
@property(retain, nonatomic) NSString *momentVideoPath; // @synthesize momentVideoPath=_momentVideoPath;
- (void)onCameraAudioOK;
- (void)onCameraAudioStop;
- (void)onCameraGap:(id)arg1;
- (void)onCameraPreviewOK;
- (void)onCameraStop;
- (void)onCameraVideoOK;
- (void)onCancel;
- (void)onCancelWithOutCamera;
- (void)onCompressFailed:(id)arg1;
- (void)onCompressOK:(id)arg1;
- (void)onExitSearch;
- (void)onGetProductInfoEnd;
- (void)onMovieCapture:(id)arg1;
- (void)onQRCodeClick;
- (void)onQRCodeFind:(id)arg1;
- (void)onQRCodeGone;
- (void)onQRCodeTrig;
- (void)onSearchContactEnd;
- (void)onSelectMomentCell;
- (void)onSelectSaveCell;
- (void)onShaky;
- (void)onShakyNormal;
- (void)onSwitchToSearchType;
- (void)onTableItemSelected:(unsigned int)arg1;
- (void)onTableViewScroll:(double)arg1;
- (void)onTopBarFrameChanged;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)onVideoVoipViewDisappear;
- (void)onWriterFailed:(id)arg1;
- (void)onWriterResign;
- (void)openKitchen;
- (void)openLightBoots;
- (void)passMovieToMomentPanel;
- (void)prepareRecord;
@property(nonatomic) int recordState; // @synthesize recordState=_recordState;
- (void)resetMotionTipsView;
- (void)reshowLightBoostButton:(_Bool)arg1;
@property(retain, nonatomic) UIImage *thumbImg; // @synthesize thumbImg=_thumbImg;
@property(retain, nonatomic) UIImage *topMask; // @synthesize topMask;
@property(retain, nonatomic) NSString *videoPath; // @synthesize videoPath=_videoPath;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (void)setupBackground;
- (void)setupButtonPanel;
- (void)setupCameraContent;
- (void)setupCameraPreview;
- (void)setupCancelBtn;
- (void)setupLineView;
- (void)setupMaskAnim;
- (void)setupMotionDetector;
- (void)setupPanView;
- (void)setupPanelMask;
- (void)setupPreviewPlayer:(id)arg1 path:(id)arg2;
- (void)setupPreviewView;
- (void)setupSendBtn;
- (void)setupTableView;
- (void)setupTitleTips;
- (void)showCancelTips;
- (void)showLightBoostButton:(_Bool)arg1;
- (void)showLightBoostButton:(_Bool)arg1 withAnim:(_Bool)arg2;
- (void)showLightBoostHint;
- (void)showTips:(id)arg1 ofColor:(id)arg2 animType:(unsigned int)arg3;
- (void)showTips:(id)arg1 ofColor:(id)arg2 animType:(unsigned int)arg3 fontSize:(double)arg4;
- (void)showTitleTips;
- (float)sightCaptureMaxDuration;
- (void)startCameraAnim;
- (void)startLightBoostAnimation;
- (void)startSendingAnim;
- (void)startWriter;
- (void)styleLightBoostButton:(_Bool)arg1;
- (void)switchToQRCodeWaiting;
- (void)switchToRecordingPanel;
- (void)switchToSendingPanel;
- (void)tryCancelPreStartRecording;
- (void)turnBtnCanceling;
- (void)turnBtnNomal;
- (void)turnBtnRecording;
- (void)turnBtnRecording:(_Bool)arg1;
- (void)turnCancelBtnForFinishRecording;
- (void)updateMask;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidPush:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBeDismissed:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

