//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IBackupExt.h"
#import "IMMWebViewKeepHolderMgrExt.h"
#import "IMusicPlayerExt.h"
#import "IOnlineClientMgrExt.h"
#import "IPublicWifiManagerExt.h"
#import "MFMassSendBannerDelegate.h"
#import "MFPushBannerDelegate.h"
#import "MFPushSystemMsgDelegate.h"

@class MFBackupBtn, MFMassSendBannerLogic, MFMusicPlayBtn, MFPublicWifiBtn, MFPushBannerLogic, MFPushSystemMsgLogic, MFWebMMBtn, MFWebViewVCKeepHoldBtn, MMVoiceSearchBar, NSMutableArray, NSString;

@interface MainFrameHeaderLogic : MMObject <MFPushBannerDelegate, MFPushSystemMsgDelegate, MFMassSendBannerDelegate, IOnlineClientMgrExt, IMusicPlayerExt, IPublicWifiManagerExt, IMMWebViewKeepHolderMgrExt, IBackupExt>
{
    MMVoiceSearchBar *m_searchBar;
    NSMutableArray *m_bannerAry;
    _Bool m_bWebWXLogined;
    _Bool m_bBakChatStarted;
    MFWebMMBtn *m_webMMBtn;
    MFMusicPlayBtn *m_musicPlayBtn;
    MFPublicWifiBtn *m_publicWifiBtn;
    MFWebViewVCKeepHoldBtn *m_webViewRecoverBtn;
    MFBackupBtn *m_backupBtn;
    MFPushBannerLogic *m_pushBannerLogic;
    MFPushSystemMsgLogic *m_pushSystemMsgLogic;
    MFMassSendBannerLogic *m_massSendBannerLogic;
    id <MainFrameHeaderDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)PopViewController;
- (void)PushViewController:(id)arg1;
- (void)addBannerBtn:(id)arg1 atIndex:(unsigned int)arg2 editable:(_Bool)arg3 withAnim:(_Bool)arg4;
- (void)addBannerBtn:(id)arg1 atIndex:(unsigned int)arg2 withAnim:(_Bool)arg3;
- (void)addBannerBtn:(id)arg1 withAnim:(_Bool)arg2;
- (void)addMassSendBanner:(id)arg1;
@property(readonly, nonatomic) unsigned long long bannerCount;
- (_Bool)cellEditable:(unsigned long long)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <MainFrameHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteBanner:(unsigned long long)arg1;
- (void)dismissPushSystemMsg;
- (void)dismissSystemMessage;
- (id)getBanner:(unsigned long long)arg1;
- (void)initBackupButton;
- (void)initHeader;
- (void)initMusicPlayBtn;
- (void)initPublicWifiBtn:(id)arg1;
- (void)initPushBanner;
- (void)initWebMMBtn;
- (id)initWithViewControllerForSearch:(id)arg1;
- (void)makeSearchBar:(id)arg1;
- (void)onBackupNotifyCode:(unsigned long long)arg1;
- (void)onBackupTransferSpeed:(float)arg1;
- (void)onCancelMassSendTask:(id)arg1;
- (void)onHidePushBanner;
- (void)onKeepHoldWebViewVCForNewMainFrameBannerStatusChangedIsAddKeep:(_Bool)arg1;
- (void)onLoginWeb;
- (void)onLogoutWeb;
- (void)onMFPushBannerFrameChanged;
- (void)onMusicPlayStatusChanged;
- (void)onProgressCurrentSession:(unsigned long long)arg1 totalSession:(unsigned long long)arg2;
- (void)onPublicWifiStatusChangedWithApBase:(id)arg1;
- (void)onRedoMassSendTask:(id)arg1;
- (void)onShowPushBanner;
- (void)onStartBackup;
- (void)onTerminateBackup;
- (void)openContactInfo:(id)arg1;
- (void)processMusicPlayBtn:(_Bool)arg1;
- (void)processPublicWifiBtn:(_Bool)arg1 apBase:(id)arg2;
- (void)registerExt;
- (void)removeBannerBtn:(id)arg1;
- (void)removeBannerBtnWithoutAnim:(id)arg1;
- (void)removeMassSendBanner:(id)arg1;
@property(readonly, nonatomic) MMVoiceSearchBar *searchBar; // @synthesize searchBar=m_searchBar;
- (void)showBackupViewController;
- (void)showCancelMusicPlay;
- (void)showLogoutWebOnline;
- (void)showPublicWifiView;
- (void)showPushSystemMsg;
- (void)showReadingWebview;
- (void)trigBanner:(unsigned long long)arg1;
- (void)unRegisterExt;
- (void)updateMusicPlayBanner;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

