//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSArray;

@interface MMAssetCell : UITableViewCell
{
    NSArray *_rowAssets;
}

- (void).cxx_destruct;
- (id)initWithAssets:(id)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
@property(retain, nonatomic) NSArray *rowAssets; // @synthesize rowAssets=_rowAssets;
- (void)setAssets:(id)arg1;

@end

