//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MultiImageScrollViewDelegate.h"

@class MultiImageScrollView, NSDictionary, NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UILabel, UIView;

@interface MMCapturePreviewBrowserController : MMUIViewController <MultiImageScrollViewDelegate>
{
    MultiImageScrollView *_pagingScrollView;
    UIView *_bottomBar;
    UIButton *_sendButton;
    UIButton *_originImageCheck;
    UILabel *_originImageLabel;
    NSMutableArray *_imageScrollViewPool;
    NSDictionary *_imageInfo;
    long long _originImageSize;
    UIActivityIndicatorView *_originIndictorView;
    _Bool _canSendOriginalImage;
    _Bool m_hasClickSendButton;
    id <ImageBrowseDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)OnCancel:(id)arg1;
- (void)OnOriginSizeGot:(id)arg1;
- (void)OnSend:(id)arg1;
@property(nonatomic) _Bool canSendOriginalImage; // @synthesize canSendOriginalImage=_canSendOriginalImage;
- (void)dealloc;
- (void)getOriginSize;
- (id)getfullScreenImage;
- (id)imageAtPage:(unsigned int)arg1;
- (id)init;
- (void)initBottomBar;
- (void)initData;
- (void)initView;
- (id)initWithImageInfo:(id)arg1;
- (_Bool)interactivePopGestureRecognizerShouldBegin:(id)arg1;
@property(nonatomic) __weak id <ImageBrowseDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) _Bool m_hasClickSendButton; // @synthesize m_hasClickSendButton;
- (void)onOriginImageCheck:(id)arg1;
- (void)onSingleTap:(id)arg1;
@property(nonatomic) long long originImageSize; // @synthesize originImageSize=_originImageSize;
- (id)viewAtPage:(unsigned int)arg1 frame:(struct CGRect)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewDidTransitionToNewSize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

