//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUILabel.h"

@class NSString, UILongPressGestureRecognizer;

@interface MMCPLabel : MMUILabel
{
    NSString *m_cpKey;
    UILongPressGestureRecognizer *m_recognizer;
    _Bool _showRestoreMenuItem;
    id <MMCPLabelDelegate> _cpLabelDelegate;
}

- (void).cxx_destruct;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
@property(retain, nonatomic) NSString *cpKey; // @synthesize cpKey=m_cpKey;
@property(nonatomic) __weak id <MMCPLabelDelegate> cpLabelDelegate; // @synthesize cpLabelDelegate=_cpLabelDelegate;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)handleLongPressGestureRecognizer:(id)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)onRestore:(id)arg1;
@property(nonatomic) _Bool showRestoreMenuItem; // @synthesize showRestoreMenuItem=_showRestoreMenuItem;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2 range:(struct _NSRange)arg3;
- (void)setText:(id)arg1 highlightKeyWord:(id)arg2 startIndex:(unsigned long long)arg3;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

