//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "crashReportConnectionDelegate.h"

@class MMCrashReportConnection, MMDBPerformRecordStatus, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface MMDBPerformReporter : NSObject <crashReportConnectionDelegate>
{
    MMCrashReportConnection *m_connection;
    NSString *m_recordStatusPath;
    MMDBPerformRecordStatus *m_recordStatus;
    NSString *m_recordPath;
    unsigned int m_recordFileSize;
    NSString *m_reportStatusPath;
    NSMutableArray *m_arrReportTime;
    _Bool m_hasCreateDataDir;
    unsigned int m_maxTimeToTiggerReport;
    unsigned int m_maxReportSize;
    unsigned int m_maxReportCount;
    id <MMDBPerformReporterDelegate> m_delegate;
    NSObject<OS_dispatch_queue> *m_workerQueue;
    NSString *m_userName;
}

- (void).cxx_destruct;
- (void)InputPerformance:(id)arg1;
- (void)addReportTime;
- (void)addSQLRecordToFile:(id)arg1;
- (void)callbackExceedMaxReportCount;
- (id)convertPerformanceToSQLRecord:(id)arg1;
- (id)currentUserName;
- (id)init;
- (_Bool)isExceedMaxRecordSize:(id)arg1;
- (_Bool)isExceedMaxReportTime;
- (_Bool)isExceedReportCount;
- (_Bool)isNeedReport:(id)arg1;
- (id)loadRecordFile;
- (void)loadRecordFileSize;
- (void)loadRecordStatus;
- (void)loadReportStatus;
@property(nonatomic) __weak id <MMDBPerformReporterDelegate> m_delegate; // @synthesize m_delegate;
@property unsigned int m_maxReportCount; // @synthesize m_maxReportCount;
@property unsigned int m_maxReportSize; // @synthesize m_maxReportSize;
@property unsigned int m_maxTimeToTiggerReport; // @synthesize m_maxTimeToTiggerReport;
@property(retain) NSString *m_userName; // @synthesize m_userName;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *m_workerQueue; // @synthesize m_workerQueue;
- (void)onReportFail;
- (void)onReportSuccess;
- (void)onUploadCrashCompleted:(_Bool)arg1 CrashWrap:(id)arg2;
- (void)perpareDataDir;
- (_Bool)removeRecordFile;
- (_Bool)removeRecordStatusFile;
- (void)renewFirstRecordTime;
- (void)reportSQLRecord:(id)arg1;
- (void)reportToServerWithSQLRecord:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

