//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMDBPerformReporterDelegate.h"
#import "MMDBPerfromStrategyDelegate.h"
#import "MMService.h"
#import "ReportStrategyExt.h"

@class MMDBPerformReporter, MMDBPerformStrategyHandler, MMDBPerformStrategyInfo, NSObject<OS_dispatch_queue>, NSString, WCDBPerformanceCollector;

@interface MMDBPerformanceMgr : MMService <MMDBPerfromStrategyDelegate, MMDBPerformReporterDelegate, ReportStrategyExt, MMService>
{
    MMDBPerformStrategyHandler *m_strategyHandler;
    WCDBPerformanceCollector *m_collector;
    MMDBPerformReporter *m_repoter;
    NSObject<OS_dispatch_queue> *m_workerQueue;
    _Bool m_hasSetup;
    MMDBPerformStrategyInfo *m_strategyInfo;
}

- (void).cxx_destruct;
- (void)OnApplicationBackgroundFetch;
- (void)ReceiveStrategyContent:(id)arg1;
- (void)SetupMonitor;
- (void)dealloc;
- (void)fetchPerformanceAndCheckReport;
- (id)init;
@property(retain) MMDBPerformStrategyInfo *m_strategyInfo; // @synthesize m_strategyInfo;
- (void)onDidActive;
- (void)onExceedMaxReportCount;
- (void)onReceiveStrategy:(int)arg1 withContene:(id)arg2;
- (void)onRenewDBPerformStrategy:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceEnterBackground;
- (void)onServiceInit;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceReloadData;
- (void)onTimerDoTheJob;
- (void)onWillSuspend;
- (void)registerExtension;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

