//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSTimer;

@interface MMGifViewMgr : NSObject
{
    NSMutableArray *m_gifs;
    NSTimer *m_timer;
    unsigned long long m_tickCount;
    NSMutableArray *m_updateQueue;
    unsigned long long m_emptyRoundTripCount;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (unsigned int)getIdKeyGifMemoryWarning;
+ (unsigned int)getIdKeyIdEmoticon;
+ (void)initialize;
+ (id)resizeToMaxWidth:(int)arg1 andMaxHeight:(int)arg2 originImage:(id)arg3;
+ (id)sharedMMGifViewMgr;
- (void).cxx_destruct;
- (void)RegisterSysNotifications;
- (void)UnRegisterSysNotifications;
- (void)addGifItem:(id)arg1;
- (void)addToUpdateQueue:(id)arg1;
- (unsigned long long)countOfGifItem;
- (unsigned long long)countOfUpdateQueue;
- (id)createGifViewFromData:(id)arg1;
- (id)createGifViewFromData:(id)arg1 withFilter:(int)arg2;
- (id)createGifViewFromFile:(id)arg1;
- (void)dealloc;
- (id)findGifItemByView:(id)arg1;
- (unsigned long long)getTickCount;
- (id)imageForGifItem:(id)arg1;
- (id)init;
- (_Bool)isSingleFrame:(id)arg1;
@property(retain, nonatomic) NSMutableArray *m_gifs; // @synthesize m_gifs;
@property(retain, nonatomic) NSTimer *m_timer; // @synthesize m_timer;
@property(retain, nonatomic) NSMutableArray *m_updateQueue; // @synthesize m_updateQueue;
- (void)onApplicationDidBecomeActive:(id)arg1;
- (void)onApplicationDidReceiveMemoryWarning:(id)arg1;
- (void)onApplicationWillResignActive:(id)arg1;
- (void)onApplicationWillTerminate:(id)arg1;
- (void)refreshGifViewUpdater:(id)arg1;
- (void)removeFromUpdateQueue:(id)arg1;
- (void)removeGifItem:(id)arg1;
- (void)startUpdateGifViews;
- (void)stopUpdateGifViews;
- (void)unregisterGifViewForUpdate:(id)arg1;
- (void)updateAllGifItem;
- (void)updateMaxWidth:(unsigned int)arg1;

@end

