//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIScrollView.h"

#import "MMImageScrollViewHelperDelegate.h"
#import "UIScrollViewDelegate.h"

@class MMImageScrollViewHelper, NSArray, NSString, UIView;

@interface MMGifPreviewScrollView : MMUIScrollView <UIScrollViewDelegate, MMImageScrollViewHelperDelegate>
{
    _Bool _isSend;
    MMImageScrollViewHelper *_scrollViewHelper;
    UIView *_zoomingView;
    id <MMGifPreviewScrollViewDelegate> _m_delegate;
}

- (void).cxx_destruct;
- (id)getScrollView;
@property(nonatomic) _Bool isSend; // @synthesize isSend=_isSend;
@property(nonatomic) __weak id <MMGifPreviewScrollViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void)onSingleTap:(id)arg1;
- (void)scrollViewDidZoom:(id)arg1;
@property(retain, nonatomic) MMImageScrollViewHelper *scrollViewHelper; // @synthesize scrollViewHelper=_scrollViewHelper;
@property(retain, nonatomic) UIView *zoomingView; // @synthesize zoomingView=_zoomingView;
- (id)viewForZooming;
- (id)viewForZoomingInScrollView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) struct CGRect frame;
@property(copy, nonatomic) NSArray *gestureRecognizers;
@property(readonly) unsigned long long hash;
@property(nonatomic) double maximumZoomScale;
@property(nonatomic) double minimumZoomScale;
@property(readonly) Class superclass;
@property(nonatomic) double zoomScale;

@end

