//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMImagePickerController, NSArray, NSData, NSDictionary, UINavigationController;

@protocol MMImagePickerControllerDelegate <NSObject>
- (void)MMImagePickerController:(MMImagePickerController *)arg1 didFinishPickingMediaWithInfo:(NSArray *)arg2;
- (void)MMImagePickerControllerDidCancel:(MMImagePickerController *)arg1;

@optional
- (void)MMImagePickerController:(MMImagePickerController *)arg1 didFinishPickingGifFileWithData:(NSData *)arg2;
- (void)MMVideoPickerController:(UINavigationController *)arg1 didFinishPickingMediaWithInfo:(NSDictionary *)arg2;
- (void)MMVideoPickerControllerDidCancel:(UINavigationController *)arg1;
@end

