//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIImage, UIImageView, UIScrollView, UIView;

@interface MMImageCropperViewController : MMUIViewController <UIScrollViewDelegate>
{
    id <MMImageCropperDelegate> _delegate;
    UIImage *_originalImage;
    UIImageView *_imageView;
    UIView *_overlayView;
    UIScrollView *_scrollView;
    struct CGRect _cropFrame;
    struct CGRect _oldFrame;
    struct CGRect _latestFrame;
}

- (void).cxx_destruct;
- (void)calculateCropFrame;
- (void)cancel:(id)arg1;
- (struct CGRect)centeredFrameForScrollView:(id)arg1 andUIView:(id)arg2;
- (void)confirm:(id)arg1;
@property(nonatomic) struct CGRect cropFrame; // @synthesize cropFrame=_cropFrame;
@property(nonatomic) id <MMImageCropperDelegate> delegate; // @synthesize delegate=_delegate;
- (id)fixOrientation:(id)arg1;
- (id)getSubImage;
- (void)handelDoubleTap:(id)arg1;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)initButton;
- (void)initScrollViewAndImageView;
- (void)initView;
- (id)initWithImage:(id)arg1;
@property(nonatomic) struct CGRect latestFrame; // @synthesize latestFrame=_latestFrame;
@property(nonatomic) struct CGRect oldFrame; // @synthesize oldFrame=_oldFrame;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
- (void)overlayClipping;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

