//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSThread;

@interface MMMonitorMgr : NSObject
{
    NSThread *m_monitorThread;
    _Bool m_bStop;
    unsigned long long m_nIntervalTime;
    _Bool m_bMonitor;
    unsigned long long m_nBlockTime;
    struct __CFRunLoopObserver *m_runLoopObserver;
    unsigned long long m_nLastTimeInterval;
    NSArray *m_arrLastMainThreadCallStack;
    struct vector<unsigned long, std::__1::allocator<unsigned long>> m_vecLastMainThreadCallStack;
    unsigned long long m_nSum;
    _Bool m_isBackgroundStartUp;
    unsigned long long m_blockDiffTime;
    float m_cpuUsage;
}

+ (id)shareInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)addMonitorThread;
- (void)addRunLoopObserver;
- (unsigned long long)check;
- (void)dealloc;
- (void)didBecomeActive;
- (void)didEnterBackground;
- (unsigned long long)diffTime:(struct timeval *)arg1 endTime:(struct timeval *)arg2;
- (void)dumpFileWithType:(unsigned long long)arg1;
- (id)init;
@property(nonatomic) _Bool m_bMonitor; // @synthesize m_bMonitor;
- (long long)needFilter;
- (void)removeRunLoopObserver;
- (void)stop;
- (void)threadProc;
- (void)willSuspend;
- (void)willTerminate;

@end

