//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "BaseScanLogicDelegate.h"
#import "FavForwardLogicDelegate.h"
#import "FavFullScreenImageViewDelegate.h"
#import "FavRecordNodeViewDelegate.h"
#import "IMsgRevokeExt.h"
#import "IRecordDownloadExt.h"
#import "MMWebViewDelegate.h"
#import "MsgRecordFileDetailDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "ViewLocationDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCNetworkMediaPlayerDelegate.h"
#import "tableViewDelegate.h"

@class CMessageWrap, FavForwardLogicController, MMTableView, MMUIWindow, NSMutableDictionary, NSString, ScanQRCodeLogicController, UIView, WCActionSheet;

@interface MsgRecordDetailViewController : MMUIViewController <MMWebViewDelegate, FavForwardLogicDelegate, WCNetworkMediaPlayerDelegate, BaseScanLogicDelegate, WCActionSheetDelegate, UITableViewDataSource, UITableViewDelegate, tableViewDelegate, FavRecordNodeViewDelegate, MsgRecordFileDetailDelegate, ViewLocationDelegate, FavFullScreenImageViewDelegate, IRecordDownloadExt, IMsgRevokeExt, UIAlertViewDelegate>
{
    MMTableView *m_tableView;
    unsigned int m_uiLongPressedIndex;
    CMessageWrap *m_recordMsg;
    MMUIWindow *m_fullScreenWindow;
    ScanQRCodeLogicController *_scanQRCodeLogic;
    int m_qrcodeActionSheetIndex;
    WCActionSheet *favImgLongPressAction;
    NSMutableDictionary *m_dictSightView;
    FavForwardLogicController *m_favForwardController;
    NSString *m_chatDate;
    NSString *m_chatDatePrefix;
    UIView *m_headerView;
    UIView *m_headerContainView;
    UIView *m_headerSepLine;
    double lastContentOffset;
    _Bool isDragging;
    unsigned int _vcType;
    NSString *_chatName;
}

- (void).cxx_destruct;
- (void)OnDownloadRecordMessageExpired:(id)arg1 DataId:(id)arg2;
- (void)OnDownloadRecordMessageFail:(id)arg1 DataId:(id)arg2;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)OnRecordMessageDownloadOK:(id)arg1;
- (void)OpenVideoFileByMsgRecordDataWrap:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)adjustViewAndNavBarRect;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSString *chatName; // @synthesize chatName=_chatName;
- (void)dealloc;
- (void)didFinishedLoading:(id)arg1;
- (void)genContent:(id)arg1 indexPath:(id)arg2;
- (void)genHeadCell:(id)arg1 indexPath:(id)arg2;
- (void)genTimeCell:(id)arg1;
- (id)getFavForawrdViewController;
- (double)getHeaderHeight;
- (double)getHeightForRowAtIndexPath:(id)arg1;
- (long long)getRowsInContentSection;
- (id)getSightFromDict:(id)arg1;
- (void)hideTopBar;
- (void)initNavigationBar;
- (void)initTableView;
- (id)initWithMsgWrap:(id)arg1;
- (void)jumpToDetail:(id)arg1;
- (void)jumpToViewStreamVideo:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onAction:(id)arg1;
- (void)onAddFavData2Fav;
- (void)onClickOnImgNode:(id)arg1 DataIndex:(unsigned int)arg2;
- (void)onClickOnNode:(id)arg1;
- (void)onClosePlayer;
- (void)onClosePlayerForViewDetail:(id)arg1;
- (void)onExitFullScreen;
- (void)onFavFullScreenImageViewHide;
- (void)onForwardFavDataWrap2Msg;
- (void)onForwardFavDataWrap2WC;
- (void)onJumpToViewDetail:(id)arg1;
- (void)onLongPressImgNode:(id)arg1;
- (void)onSaveFavDataImg;
- (void)onScanEnds;
- (void)onSendLocationToFriend:(id)arg1 ViewController:(id)arg2;
- (void)onWillLongPressImgNode:(id)arg1;
- (void)pulseAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)removeSightFromDict:(id)arg1;
- (void)resetHeader:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)selectFileData:(id)arg1;
- (void)selectGoodsData:(id)arg1;
- (void)selectLocationData:(id)arg1;
- (void)selectMallProductData:(id)arg1;
- (void)selectMusicData:(id)arg1;
- (void)selectSigthData:(id)arg1;
- (void)selectTVData:(id)arg1;
- (void)selectUrlData:(id)arg1;
- (void)selectVideoData:(id)arg1;
@property(nonatomic) unsigned int vcType; // @synthesize vcType=_vcType;
- (void)showTopBar;
- (_Bool)stopAtLastVideoFrameWhenPlayEnd;
- (void)storeSightToDict:(id)arg1 withKey:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)useTransparentNavibar;
- (void)viewDidLoad;
- (void)viewDidTransitionToNewSize;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

