//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

@class MMUIView, MultiTalkContactItem, MultiTalkMessageItem, MultiTalkSessionDetailMemberCellView, MultiTalkSessionItem, NSArray, UIScrollView, VoipDescriptionButton;

@interface MulitTalkMessageDetailViewController : MMUIViewController
{
    unsigned int _localMsgID;
    MultiTalkSessionItem *_sessionItem;
    MultiTalkMessageItem *_messageItem;
    MultiTalkContactItem *_contactItem;
    NSArray *_memberList;
    UIScrollView *_contentView;
    MMUIView *_roomStatusView;
    MultiTalkSessionDetailMemberCellView *_memberView;
    VoipDescriptionButton *_enterCallButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MultiTalkContactItem *contactItem; // @synthesize contactItem=_contactItem;
@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
- (void)dealloc;
@property(retain, nonatomic) VoipDescriptionButton *enterCallButton; // @synthesize enterCallButton=_enterCallButton;
- (id)getMsgDisplayContent;
- (void)initData;
- (void)initView;
- (id)initWithMultiTalkSessionItem:(id)arg1 msgLocalID:(unsigned int)arg2;
- (_Bool)isGroupHasMemberActive;
- (_Bool)isGroupNormalHangout;
@property(nonatomic) unsigned int localMsgID; // @synthesize localMsgID=_localMsgID;
@property(retain, nonatomic) NSArray *memberList; // @synthesize memberList=_memberList;
@property(retain, nonatomic) MultiTalkSessionDetailMemberCellView *memberView; // @synthesize memberView=_memberView;
@property(retain, nonatomic) MultiTalkMessageItem *messageItem; // @synthesize messageItem=_messageItem;
- (void)onEnterMultiTalkBtnPress:(id)arg1;
- (void)popViewControllerNoAnimation;
@property(retain, nonatomic) MMUIView *roomStatusView; // @synthesize roomStatusView=_roomStatusView;
@property(retain, nonatomic) MultiTalkSessionItem *sessionItem; // @synthesize sessionItem=_sessionItem;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

