//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMService.h"
#import "OnGotAppMsgHandleDelegate.h"
#import "SendAppMsgHandleDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCPayOpenApiExt.h"

@class AppAddCardHandler, AppJumpLogicHelper, BaseOpenSDKHandler, ChooseCardHandler, ChooseInvoiceHandler, JumpToBizWebviewHandler, NSMutableDictionary, NSString, NewAuthHandler, OnGotAppMsgHandler, OpenProfileHandler, OpenRankListHandler, OpenTempSessionHandler, OpenWebviewHandler, SMSAddCardHandler, SendAppMsgHandler, SendAppMsgToFavoritesHandler, SendAppMsgToWCHandler, WeChatHBHandler, WeChatPayHandler, WechatConnectHandler;

@interface OpenApiMgr : MMService <MMService, IMsgExt, WCActionSheetDelegate, WCPayOpenApiExt, SendAppMsgHandleDelegate, OnGotAppMsgHandleDelegate>
{
    SendAppMsgHandler *m_oSendAppMsgHandler;
    OnGotAppMsgHandler *m_oOnGotAppMsgHandler;
    WechatConnectHandler *m_oWechatConnectHandler;
    SendAppMsgToWCHandler *m_oSendAppMsgToWCHandler;
    SendAppMsgToFavoritesHandler *m_oSendAppMsgToFavoritesHandler;
    WeChatPayHandler *m_oWeChatPayHandler;
    WeChatHBHandler *m_oWeChatHBHandler;
    NewAuthHandler *m_oNewAuthHandler;
    AppJumpLogicHelper *m_oAppJumpHandler;
    OpenProfileHandler *m_oOpenProfileHandler;
    JumpToBizWebviewHandler *m_oJumpBizWebHandler;
    SMSAddCardHandler *m_oSMSAddCardHandler;
    AppAddCardHandler *m_oAppAddCardHandler;
    OpenTempSessionHandler *m_oOpenTempSessionHandler;
    OpenWebviewHandler *m_oOpenWebviewHandler;
    OpenRankListHandler *m_oOpenRankListHandler;
    BaseOpenSDKHandler *m_oBaseOpenSDKHandler;
    ChooseCardHandler *m_oChooseCardHandler;
    ChooseInvoiceHandler *m_oChooseInvoiceHandler;
    NSMutableDictionary *m_paraDic;
    _Bool m_uiIsInternalDownload;
}

- (void).cxx_destruct;
- (void)OnEndWithOnGotAppMsgHandle:(id)arg1;
- (void)OnPreAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnStayAtWechatWithSendAppMsgHandle:(id)arg1;
- (void)cancelAllApi;
- (void)cancelAppAddCard;
- (void)cancelChooseCard;
- (void)cancelChooseInvoice;
- (void)cancelJumpToBizWebview;
- (void)cancelNewAuth;
- (void)cancelOnGotAppMsgHandler;
- (void)cancelOpenProfile;
- (void)cancelOpenRankList;
- (void)cancelOpenSDKHandler;
- (void)cancelOpenTempSession;
- (void)cancelOpenWebview;
- (void)cancelSMSAddCard;
- (void)cancelSendAppMsgHandler;
- (void)cancelSendAppMsgToFavorites;
- (void)cancelSendAppMsgToWCHandler;
- (void)cancelWechatConnectHandler;
- (void)cancelWechatHB;
- (void)cancelWechatPay;
- (_Bool)checkSupportCommand:(unsigned int)arg1;
- (void)dealloc;
- (void)doApi:(id)arg1 bundleId:(id)arg2;
- (void)doAppAddCard:(id)arg1 BundleID:(id)arg2 Info:(id)arg3;
- (void)doChooseCard:(id)arg1 BundleID:(id)arg2 Info:(id)arg3;
- (void)doChooseInvoice:(id)arg1 BundleID:(id)arg2 Info:(id)arg3;
- (void)doCreateChatRoom:(id)arg1 bundleId:(id)arg2 info:(id)arg3;
- (void)doJumpToBizWebview:(id)arg1 BundleID:(id)arg2 Info:(id)arg3;
- (void)doOAuthOpenApi:(id)arg1 authInfo:(id)arg2;
- (void)doOpenProfileApi:(id)arg1 BundleID:(id)arg2 Info:(id)arg3;
- (void)doOpenRankListWithAppId:(id)arg1 bundleId:(id)arg2 info:(id)arg3;
- (void)doOpenTempSessionWithAppId:(id)arg1 bundleId:(id)arg2 info:(id)arg3;
- (void)doOpenWebviewWithAppId:(id)arg1 bundleId:(id)arg2 info:(id)arg3;
- (void)doSMSAddCardApi:(id)arg1;
- (void)doWCHBOpenApi:(id)arg1 BundleID:(id)arg2 payInfo:(id)arg3;
- (void)doWCPayOpenApi:(id)arg1 BundleID:(id)arg2 payInfo:(id)arg3;
- (void)doWCPayWapWithPayInfo:(id)arg1;
- (id)getAppIdByFunctionType:(int)arg1;
- (id)init;
- (_Bool)isCanJumpWithAppId:(id)arg1;
- (_Bool)isInternalDownload;
- (_Bool)isShowAppMessageBottom:(id)arg1;
- (_Bool)isShowTimeLineJumpLink:(id)arg1;
- (_Bool)isShowTimelineSource:(id)arg1;
- (void)joinChatRoom:(id)arg1 bundleId:(id)arg2 info:(id)arg3;
- (_Bool)jumpByAppIdInMessage:(id)arg1;
- (_Bool)jumpByAppIdInTimeline:(id)arg1;
- (void)jumpToInstallUrl:(id)arg1;
- (void)jumpToInstallUrl:(id)arg1 isInternalDownload:(_Bool)arg2;
- (_Bool)launch3rdApp:(id)arg1;
- (void)onMMConfigUpdated;
- (void)onServiceEnterBackground;
- (void)onServiceInit;
- (void)onServiceTerminate;
- (void)readConfig;
- (_Bool)sendOpenTempSessionRespToApp:(id)arg1 errCode:(int)arg2 notifyStr:(id)arg3;
- (_Bool)sendReq:(id)arg1 conversationAccount:(id)arg2 toApp:(id)arg3;
- (_Bool)sendReqLaunchApp:(id)arg1 withMediaInternalMessage:(id)arg2;
- (int)sendReqLaunchAppWithRet:(id)arg1 withMediaInternalMessage:(id)arg2;
- (_Bool)sendReqShowMessage:(id)arg1 toApp:(id)arg2;
- (_Bool)sendResp:(id)arg1 toApp:(id)arg2;
- (_Bool)sendWCAddCardResp:(id)arg1 toApp:(id)arg2 errCode:(int)arg3;
- (_Bool)sendWCChooseCardResp:(id)arg1 toApp:(id)arg2 errCode:(int)arg3;
- (_Bool)sendWCChooseInvoiceResp:(id)arg1 toApp:(id)arg2 errCode:(int)arg3;
- (_Bool)sendWCHBResp:(id)arg1 toApp:(id)arg2;
- (_Bool)sendWCPayResp:(id)arg1 toApp:(id)arg2;
- (void)setIsInternalDownload:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

