//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface OPItemWrap : NSObject
{
    NSString *_word;
    NSString *_url;
    UIColor *_wordColor;
    NSString *_icon;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *word; // @synthesize word=_word;
@property(retain, nonatomic) UIColor *wordColor; // @synthesize wordColor=_wordColor;

@end

