//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMMDB, NSMutableArray, NSRecursiveLock;

@interface OplogDataLogic : NSObject
{
    unsigned int m_oplogStartRowID;
    _Bool m_bNeedContinue;
    NSMutableArray *m_arrOplogs;
    CMMDB *m_oMMDB;
    NSRecursiveLock *m_oLock;
}

- (void).cxx_destruct;
- (void)checkNeedContiue;
- (void)deleteOplog:(unsigned int)arg1;
- (id)initWithDB:(id)arg1 lock:(id)arg2;
- (id)loadOplogFromDBlimit:(unsigned int)arg1;
@property _Bool m_bNeedContinue; // @synthesize m_bNeedContinue;
- (unsigned int)setFailOplog:(unsigned int)arg1;

@end

