//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSRecursiveLock;

@interface Q2DMapStatistics : NSObject
{
    NSMutableDictionary *_tileTimes;
    NSRecursiveLock *_lock;
}

+ (id)sharedStatistics;
- (void).cxx_destruct;
- (id)DPI;
- (void)addTileElpaseTime:(float)arg1 type:(int)arg2;
- (id)appBundleIdentifier;
- (id)appName;
- (id)appVersion;
- (id)appendCommonUrlStatisticParamatersFor:(id)arg1;
- (id)constructArguments;
- (id)constructCommonArguments;
- (id)constructRequest;
- (id)constructURLStringWithArguments:(id)arg1 forUrl:(id)arg2;
- (id)deviceIdentifier;
- (id)init;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
- (id)netType;
- (void)reportTileStatistics;
- (void)sendingRequest:(id)arg1:(CDUnknownBlockType)arg2;
- (void)sendingStatisticsToServer:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableDictionary *tileTimes; // @synthesize tileTimes=_tileTimes;
- (void)throwKeyInvalidException;

@end

