//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QDataSourceProtocol.h"

@class NSString;

@interface QDataSourceBase : NSObject <QDataSourceProtocol>
{
    id <QDataCacheProtocol> _dataCache;
    NSString *_version;
    NSString *_styleId;
    NSString *_sceneId;
    unsigned long long _mapLanguage;
}

- (void).cxx_destruct;
- (void)clearCacheByStyle;
- (void)clearDataCache;
@property(retain, nonatomic) id <QDataCacheProtocol> dataCache; // @synthesize dataCache=_dataCache;
- (id)initWithDataCache:(id)arg1;
- (_Bool)isValidForTile:(CDStruct_74b02b43)arg1;
- (_Bool)isValidForTileData:(id)arg1;
@property(readonly, nonatomic) NSString *lauguageCode;
@property(nonatomic) unsigned long long mapLanguage; // @synthesize mapLanguage=_mapLanguage;
@property(readonly, nonatomic) long long maxZoomLevel;
@property(readonly, nonatomic) long long minZoomLevel;
@property(copy, nonatomic) NSString *sceneId; // @synthesize sceneId=_sceneId;
@property(copy, nonatomic) NSString *styleId; // @synthesize styleId=_styleId;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
- (_Bool)shouldCollectRequestTime;
- (void)throwNotificationForError:(id)arg1;
- (id)tileData:(CDStruct_74b02b43)arg1;
- (id)tileImage:(CDStruct_74b02b43)arg1 needFresh:(_Bool *)arg2;
- (id)tilePath:(CDStruct_74b02b43)arg1;
@property(readonly, nonatomic) double tileSize;
- (int)tileType;
- (id)tileURL:(CDStruct_74b02b43)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

