//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "IPreEnterWechatLogicExt.h"
#import "SessionSelectControllerDelegate.h"
#import "ShareMessageConfirmLogicHelperDelegate.h"
#import "UIAlertViewDelegate.h"

@class AppCommunicateData, CContact, CMessageWrap, ForwardMessageLogicController, MMUINavigationController, NSString, UIAlertView;

@interface SendAppMsgHandler : MMObject <SessionSelectControllerDelegate, ShareMessageConfirmLogicHelperDelegate, UIAlertViewDelegate, IPreEnterWechatLogicExt>
{
    NSString *m_nsAppid;
    NSString *m_nsBundleId;
    AppCommunicateData *m_appData;
    CMessageWrap *m_messageWrap;
    CContact *m_oContact;
    UIAlertView *m_alertView;
    _Bool m_bIsHiddenTarBar;
    int m_Scene;
    NSString *m_nsRedirectUrl;
    ForwardMessageLogicController *m_forwardMsgLogic;
    unsigned int m_uiSessionSelectConfirmType;
    id <SendAppMsgHandleDelegate> m_delegate;
    MMUINavigationController *_m_navigationController;
}

- (void).cxx_destruct;
- (void)OnForwardMessageBackToApp:(id)arg1;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageException:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (void)OnForwardMessageStayAtWeChat:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)asyncNotifySendAppMsgOk;
- (void)cancelAllHandle;
- (void)cancelAllHandleAndReturn3rdApp;
- (void)cancelSendAppMsg;
- (void)clearAllHandle;
- (void)clearAllHandleAndReturn3rdApp:(_Bool)arg1;
- (void)dealloc;
- (void)doAppAuth;
- (id)getCurrentViewController;
- (id)init;
@property(nonatomic) int m_Scene; // @synthesize m_Scene;
@property(nonatomic) __weak id <SendAppMsgHandleDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) MMUINavigationController *m_navigationController; // @synthesize m_navigationController=_m_navigationController;
- (void)removeAuthViewController;
- (void)sendAppMsg:(id)arg1;
- (void)sendAppMsg:(id)arg1 bundleId:(id)arg2 withData:(id)arg3;
- (void)shareAuthViewControllerDidCancel:(id)arg1;
- (void)shareAuthViewControllerDidFail:(id)arg1;
- (void)shareAuthViewControllerDidSuccess:(id)arg1 redirectUrl:(id)arg2;
- (void)showAlertView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

