//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableArray, NSString, WCStatTimerHelper;

@interface SessionActionStatMgr : MMService <MMService>
{
    NSMutableArray *_actionList;
    _Bool _bDidEnterChatRoom;
    unsigned int _uiStayWebViewTime;
    WCStatTimerHelper *_oStatTimerHelper;
    struct map<unsigned long, NSMutableDictionary *, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, NSMutableDictionary *>>> _mapExpourseTypeToDic;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)clearExposureMsgIdDic;
- (void)dealloc;
- (void)enterChatRoom;
- (void)exitChatRoom:(id)arg1 beginTime:(unsigned int)arg2 unreadCount:(unsigned int)arg3;
- (id)getFromChatRoomWithMsgWrap:(id)arg1;
- (unsigned int)getMaxCacheLogCount;
- (unsigned int)getMaxCacheTime;
- (id)getPosterUserNameWithMsgWrap:(id)arg1;
- (int)getSessionTypeWithContact:(id)arg1;
- (_Bool)hadExposuredWithMessageId:(unsigned long long)arg1 expourseType:(unsigned long long)arg2;
- (_Bool)isMessageWrapInExp:(id)arg1;
- (void)logAppMessageExpourse:(id)arg1;
- (void)logExpMessageClick:(id)arg1 mediaState:(int)arg2;
- (void)logExpMessageExpourse:(id)arg1 mediaState:(int)arg2;
- (void)markExposuredWithMessageId:(unsigned long long)arg1 expourseType:(unsigned long long)arg2;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (id)pathForSessionActionCache;
- (void)recordStayWebViewTimeInMS:(unsigned long long)arg1;
- (_Bool)saveSessionActionCache;
- (_Bool)tryLoadSessionActionCache;
- (void)tryUploadActionList;
- (void)uploadActionList;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

