//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "IMsgExt.h"
#import "IMsgRevokeExt.h"
#import "ISightExt.h"
#import "IVOIPUILogicMgrExt.h"
#import "IVideoExt.h"
#import "IWXVideoPlayerViewExt.h"
#import "SightIconViewDelegate.h"
#import "SightPlayerViewDelegate.h"
#import "SightViewDelegate.h"

@class NSString, SightView, UIImageView;

@interface ShortVideoMessageNodeView : BaseMessageNodeView <IVOIPUILogicMgrExt, IWXVideoPlayerViewExt, SightViewDelegate, IMsgRevokeExt, IVideoExt, IMsgExt, SightPlayerViewDelegate, SightIconViewDelegate, ISightExt>
{
    UIImageView *m_thumbImg;
    SightView *_playerView;
    struct CGRect m_vedioFrame;
    _Bool m_isLoading;
    _Bool m_isClickDownload;
    unsigned long long _sightLegalityType;
    _Bool _mayBeIllegalAD;
    _Bool _isVideoExpired;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)OnMsgDownloadVideoExpiredFail:(id)arg1 MsgWrap:(id)arg2;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)OnSightThumbDidChange:(id)arg1;
- (void)OnSightThumbDownloadFailed:(id)arg1;
- (void)OnSightThumbDownloadOK:(id)arg1;
- (void)OnUpdateVideoStatus:(id)arg1 MsgWrap:(id)arg2;
- (void)OnVideoGetIntoUploadQueue:(id)arg1;
- (void)UpdateSightVideoDownloadMsg:(id)arg1;
- (void)UpdateVideoMsg:(id)arg1;
- (_Bool)canAutoPlaySettingFromServer;
- (void)checkLegalityWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)clearShortVideo;
- (void)commonInit;
- (void)configSubviews;
- (void)dealloc;
- (_Bool)generateThumbImage;
- (id)getMessageDisplayView;
- (void)handleDownloadFail;
- (id)initWithMessageWrap:(id)arg1 Contact:(id)arg2 ChatContact:(id)arg3;
- (_Bool)isInFlowControl;
- (_Bool)isSendFailed;
- (_Bool)isSightFileExist;
- (_Bool)isSightVideoPlayable;
- (void)layoutSubviews;
- (void)layoutSubviewsInternal;
- (id)makeRecieverMaskLayer;
- (id)makeRecieverPath:(double)arg1;
- (id)makeSenderMaskLayer;
- (id)makeSenderPath:(double)arg1;
- (void)notifySuperViewToRefresh;
- (void)onAppear;
- (void)onClick;
- (void)onFavoriteAdd:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onLongTouch;
- (void)onMoreOperate:(id)arg1;
- (void)onProgressEnd;
- (void)onResumeSightView:(id)arg1;
- (void)onStackSightView:(id)arg1;
- (void)onTouchUpInside;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)onVideoVoipViewDisappear;
- (void)onWXVideoPlayerViewPlay:(id)arg1;
- (void)playShortVideo;
- (void)reLayoutSubviews;
- (void)setProgress:(unsigned int)arg1;
- (void)setThumbImage:(id)arg1;
- (_Bool)shouldAutoDownloadDefault;
- (_Bool)shouldAutoDownloadForExp;
- (_Bool)shouldAutoPlay;
- (void)showOpearation;
- (id)sightVideoPath;
- (_Bool)sightView:(id)arg1 playbackDidReadEnd:(_Bool)arg2;
- (void)sightViewProgressDidReachEnd:(id)arg1;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)stopPlayShortVideo;
- (id)thumbImage;
- (id)thumbImagePath;
- (void)updateUIAfterThumbImageDidReGenerate;
- (struct CGSize)videoSizeForThumbSize:(struct CGSize)arg1;
- (void)willMoveToSuperview:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

