//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "StoreEmotionBaseCgi.h"

@class EmoticonStoreItem;

@interface StoreEmotionExchangeEmotionPackCgi : StoreEmotionBaseCgi
{
    EmoticonStoreItem *m_storeItem;
    id <StoreEmotionExchangeEmotionPackCgiDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <StoreEmotionExchangeEmotionPackCgiDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleErrorReturn;
- (void)handleMessageReturnWithResponse:(id)arg1;
- (id)init;
- (_Bool)startRequestWithProductId:(id)arg1 reqScene:(int)arg2 IsAutomatic:(_Bool)arg3;
- (_Bool)startRequestWithStoreItem:(id)arg1 reqScene:(int)arg2 IsAutomatic:(_Bool)arg3;

@end

