//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ICdnComMgrExt.h"

@class CdnTaskInfo, NSMutableArray, NSString;

@interface UploadShortVideoToCdn : MMObject <ICdnComMgrExt>
{
    NSMutableArray *_arrUploadTask;
    CdnTaskInfo *_curTaskInfo;
    unsigned int _curUploadEventID;
    id <UploadShortVideoDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)CheckQueue;
- (void)DelTaskInUploadQueue:(id)arg1;
- (_Bool)IsMsgInUploadQueue:(id)arg1;
- (void)MassSendSightFail;
- (void)MassSendSightOK;
- (void)OnCdnUpload:(id)arg1;
- (void)OnCdnUploadProgress:(id)arg1;
- (void)OnSetCdnDnsInfo;
- (void)StartUpload:(id)arg1;
- (void)StopAll;
- (void)StopCurUpload;
- (void)StopUpload:(id)arg1;
- (void)clearTask;
- (void)dealloc;
- (id)init;
@property(nonatomic) __weak id <UploadShortVideoDelegate> m_delegate; // @synthesize m_delegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

