//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VideoEncodeParams : NSObject
{
    _Bool _videoOnly;
    float _width;
    float _height;
    float _fps;
    float _videoBitrate;
    float _frameInterval;
    float _audioBitrate;
}

@property(nonatomic) float audioBitrate; // @synthesize audioBitrate=_audioBitrate;
- (id)description;
@property(nonatomic) float fps; // @synthesize fps=_fps;
@property(nonatomic) float frameInterval; // @synthesize frameInterval=_frameInterval;
@property(nonatomic) float height; // @synthesize height=_height;
@property(nonatomic) float videoBitrate; // @synthesize videoBitrate=_videoBitrate;
@property(nonatomic) _Bool videoOnly; // @synthesize videoOnly=_videoOnly;
@property(nonatomic) float width; // @synthesize width=_width;

@end

