//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "VoicePrintLogicControllerDelegate.h"

@class NSString, UIViewController, VoicePrintLogicControllerFactory;

@interface VoicePrintHandler : MMObject <VoicePrintLogicControllerDelegate>
{
    VoicePrintLogicControllerFactory *m_VoicePrintLogicController;
    _Bool m_bPresentViewController;
    id <VoicePrintHandlerDelegate> m_delegate;
    UIViewController *m_viewController;
    NSString *nsTicket;
    unsigned long long uiMaxVerifyTryTimes;
    NSString *nsShowUrlWhenOverMaxVerifyTimes;
}

- (void).cxx_destruct;
- (void)OnClickCanNotUnLockBtn;
- (void)OnVerifyOverLimitFromServer;
- (void)OnVerifySuccessful;
- (void)OpenLogin;
- (void)OpenRsaVerify;
- (void)OpenVerify;
- (void)OpenVoicePrintViewForLogin;
- (void)OpenVoicePrintViewWithType:(int)arg1;
- (id)getNavigationController;
- (id)getViewController;
- (id)init;
@property(nonatomic) __weak id <VoicePrintHandlerDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) __weak UIViewController *m_viewController; // @synthesize m_viewController;
@property(retain, nonatomic) NSString *nsShowUrlWhenOverMaxVerifyTimes; // @synthesize nsShowUrlWhenOverMaxVerifyTimes;
@property(retain, nonatomic) NSString *nsTicket; // @synthesize nsTicket;
@property(nonatomic) unsigned long long uiMaxVerifyTryTimes; // @synthesize uiMaxVerifyTryTimes;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

