//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VOIPSettingUtil : NSObject
{
}

+ (id)getParamOfKey:(id)arg1 defaultVal:(id)arg2;
+ (id)getVoipSettingConfigRootDir;
+ (id)getVoipSettingConfinPath;
+ (_Bool)saveParams:(id)arg1;

@end

