//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSString, UINavigationController, WAContactGetter;

@interface WAAppContactPreLoader : MMService <MMService>
{
    NSString *m_userNameOfNewContact;
    UINavigationController *m_navigationViewController;
    CDUnknownBlockType m_successBlock;
    CDUnknownBlockType m_faildBlock;
    unsigned long long m_enterScene;
    NSString *m_sceneNote;
    NSString *m_pagePath;
    unsigned long long m_debugMode;
    unsigned int m_version;
    WAContactGetter *m_contactGetter;
}

- (void).cxx_destruct;
- (void)cancelReqeustNewContact;
- (id)checkIfNeedEnterErrPageURL:(id)arg1;
- (void)clearState;
- (void)dealloc;
- (void)enterAppWithContact:(id)arg1;
- (void)finalyOpenAppWithContact:(id)arg1 extInfo:(id)arg2;
- (_Bool)isNeedDevAppContact;
- (void)openAppContact;
- (void)openAppWithQRFullUrl:(id)arg1 fromScene:(unsigned long long)arg2;
- (void)openAppWithUserName:(id)arg1 navigationController:(id)arg2 fromScene:(unsigned long long)arg3 debugMode:(unsigned long long)arg4 onSuccess:(CDUnknownBlockType)arg5 onFailed:(CDUnknownBlockType)arg6;
- (void)openAppWithUserName:(id)arg1 navigationController:(id)arg2 fromScene:(unsigned long long)arg3 sceneNote:(id)arg4 onSuccess:(CDUnknownBlockType)arg5 onFaild:(CDUnknownBlockType)arg6;
- (void)openAppWithUserName:(id)arg1 navigationController:(id)arg2 fromScene:(unsigned long long)arg3 sceneNote:(id)arg4 pagePath:(id)arg5 debugMode:(unsigned long long)arg6 version:(unsigned int)arg7 onSuccess:(CDUnknownBlockType)arg8 onFailed:(CDUnknownBlockType)arg9;
- (void)openAppWithUserName:(id)arg1 navigationController:(id)arg2 fromScene:(unsigned long long)arg3 sceneNote:(id)arg4 pagePath:(id)arg5 onSuccess:(CDUnknownBlockType)arg6 onFailed:(CDUnknownBlockType)arg7;
- (void)openErrWebViewControllerWithUrl:(id)arg1 navigationController:(id)arg2;
- (id)queryParamDictFromFullUrl:(id)arg1;
- (void)reportErrorPageEventWithPageType:(unsigned long long)arg1 Contact:(id)arg2 debugMode:(unsigned long long)arg3;
- (void)showDeviceForbbidenWebView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

