//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCDataBase, WCDataBaseTable;

@interface WAAppTaskDB : NSObject
{
    NSString *_appID;
    WCDataBase *_db;
    WCDataBaseTable *_tableDownloadFileURLInfo;
    WCDataBaseTable *_tableLocalStorageMainInfo;
    WCDataBaseTable *_tableLocalStorageDataInfo;
}

- (void).cxx_destruct;
- (void)addDownloadFileURL:(id)arg1 withLocalID:(id)arg2;
- (void)clearLocalStorage;
- (void)close;
- (void)dealloc;
- (id)getDonwloadFileLocalIDWithURL:(id)arg1;
- (id)getLocalStorageAllKeys;
- (void)getLocalStorageData:(id *)arg1 dataType:(id *)arg2 withKey:(id)arg3;
- (unsigned int)getLocalStorageKeyAndDataLengthWithKey:(id)arg1;
- (unsigned long long)getLocalStorageMainStorageLength;
- (id)initWithAppID:(id)arg1;
- (void)open;
- (void)openTable;
- (void)removeDownloadFileLocalID:(id)arg1;
- (void)removeDownloadFileURL:(id)arg1;
- (_Bool)removeLocalStorageDataWithKey:(id)arg1;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1 stateDidChanged:(CDUnknownBlockType)arg2;
- (_Bool)setLocalStorageData:(id)arg1 dataType:(id)arg2 withKey:(id)arg3 lastModifyTime:(unsigned int)arg4;
- (_Bool)setLocalStorageMainStorageLength:(unsigned long long)arg1 lastModifyTime:(unsigned int)arg2;
- (id)setupTableWithName:(id)arg1 tableClass:(Class)arg2;

@end

