//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WAAppTaskLoaderContextDelegate.h"
#import "WALoadingViewControllerDelegate.h"

@class NSString, WAAppTaskLoaderContext, WALoadingViewController, WASerialWorkFlow;

@interface WAAppTaskLoader : NSObject <WALoadingViewControllerDelegate, WAAppTaskLoaderContextDelegate>
{
    NSString *_appID;
    WAAppTaskLoaderContext *_context;
    CDUnknownBlockType _completeHandler;
    id <WAAppTaskLoaderDelegate> _loaderDelegate;
    WASerialWorkFlow *_firstPageWorkFlow;
    WASerialWorkFlow *_childPageWorkFlow;
    WALoadingViewController *_loadingVC;
}

+ (void)childAsyncStepOrConditionLoad:(id)arg1 context:(id)arg2;
+ (void)childStepPushWebView:(id)arg1;
+ (void)childStepSetupWebView:(id)arg1;
+ (_Bool)getHomePageBaseURL:(id *)arg1 pageRelativeURL:(id *)arg2 withAppID:(id)arg3 contact:(id)arg4 getError:(id *)arg5;
+ (id)getInfoDataWithAppID:(id)arg1 contact:(id)arg2;
+ (void)stepAsyncAndConditionLoad:(id)arg1 context:(id)arg2;
+ (void)stepAsyncOrConditionLoad:(id)arg1 context:(id)arg2;
+ (void)stepSetupAppServiceAndWebView:(id)arg1;
+ (void)substepAsyncOnInitReady:(id)arg1;
+ (void)substepAsyncOnTimeout:(id)arg1 millisecond:(long long)arg2;
+ (void)substepCheckCacheVersion:(id)arg1;
+ (void)substepCheckPermissionBytes:(id)arg1;
- (void).cxx_destruct;
- (id)appID;
- (void)callCompleteHandler:(_Bool)arg1 isUserAbort:(_Bool)arg2 error:(id)arg3;
- (void)cancelFirstPageWorkFlow;
- (void)dealloc;
- (void)getChildWebView:(id *)arg1 withRelativeURL:(id)arg2 childExtraInfo:(id)arg3 fromParentWebView:(id)arg4;
- (id)initWithAppID:(id)arg1;
- (void)loadChildPageWithDelegate:(id)arg1 context:(id)arg2 completeHandler:(CDUnknownBlockType)arg3;
- (void)loadFirstPageWithDelegate:(id)arg1 context:(id)arg2 completeHandler:(CDUnknownBlockType)arg3;
- (void)onAppBrandLoadingViewReturn:(id)arg1;
- (void)onBeforePushWebView;
- (void)onLoadingAnimationDone;
- (void)popLoadingView;
- (void)releaseLoadingView;
- (void)removeChildWebView:(id)arg1 fromParentWebView:(id)arg2;
- (void)removeChildWebViewOnFail;
- (void)removeParentWebView:(id)arg1;
- (void)runChildPageWorkFlow;
- (void)runFirstPageWorkFlow;
- (void)setupAppServiceAndWebViewWithAppID:(id)arg1 contact:(id)arg2 baseURL:(id)arg3 pageRelativeURL:(id)arg4 getWebView:(id *)arg5;
- (void)showLoadingView;
- (void)stepPushWebView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

