//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMResourceMgrExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSDictionary, NSMutableDictionary, NSString, WAAppBrandNotifyStorage;

@interface WAConfigMgr : MMService <MMResourceMgrExt, IMsgExt, PBMessageObserverDelegate, MMService>
{
    NSMutableDictionary *_dicAppID2ConfigJSON;
    NSMutableDictionary *_dicAppID2ContactAttribute;
    WAAppBrandNotifyStorage *m_notifyStorage;
    NSMutableDictionary *dicUseVConsoleApp;
    NSDictionary *_dicSystemConfig;
    NSString *_mmUserAgent;
}

+ (_Bool)isOpenFindFriendEntry;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)appConfigJSONCategoryOnServiceClearData;
- (void)appConfigJSONCategoryOnServiceInit;
- (void)appConfigJSONCategoryOnServiceReloadData;
- (id)appConfigJsonTextForAppService:(id)arg1;
- (void)asyncUpdateWeAppConfigInfo:(id)arg1;
- (_Bool)closeUseVConsoleWithAppID:(id)arg1;
- (void)contactAttributeCategoryOnServiceClearData;
- (void)contactAttributeCategoryOnServiceInit;
- (void)contactAttributeCategoryOnServiceReloadData;
- (id)contactAttributeWithAppID:(id)arg1;
- (void)dealloc;
- (void)deleteDebugModeAppInfo:(id)arg1 debugType:(unsigned long long)arg2;
@property(retain) NSDictionary *dicSystemConfig; // @synthesize dicSystemConfig=_dicSystemConfig;
- (id)dictionaryForAppID:(id)arg1 andPaths:(id)arg2;
- (id)entryPagePathForAppID:(id)arg1;
- (id)exposeURLWithAppid:(id)arg1 msgid:(id)arg2;
- (id)exposeURLWithAppid:(id)arg1 pageid:(id)arg2;
- (id)forbbidenUrlWithAppid:(id)arg1;
- (id)getAllDebugModeAppInfo;
- (id)getAllDebugModeAppInfoForceSave:(_Bool)arg1;
- (id)getAppWebPageFullUrlWithAppid:(id)arg1 version:(unsigned long long)arg2 relativePath:(id)arg3 isDebugMode:(unsigned long long)arg4;
- (id)getCdnBaseUrlStrIsDebugMode:(unsigned long long)arg1;
- (id)getDebugPkgDownloadUrlWithAppid:(id)arg1 debugType:(unsigned long long)arg2;
- (id)getDebugPkgValidTimeStrWithAppid:(id)arg1 debugType:(unsigned long long)arg2;
- (id)getDeubgModeAppInfoByName:(id)arg1 debugType:(unsigned long long)arg2;
- (id)getMMUserAgent;
- (id)getPublicResDebugModeAppInfo;
- (id)getSaveInfoKeyWithAppid:(id)arg1 debugType:(unsigned int)arg2;
- (id)init;
- (void)insertDeubgModeAppInfo:(id)arg1;
- (_Bool)isDebugModeAlreadyUpdatePkgWithAppid:(id)arg1 debugType:(unsigned long long)arg2;
- (_Bool)isDebugModeAppWithUserName:(id)arg1;
- (void)loadAppConfigWithAppID:(id)arg1 data:(id)arg2;
- (void)loadNotifyStorage;
- (void)loadSystemSettingData;
- (id)lowVersionWithAppid:(id)arg1;
@property(retain) NSString *mmUserAgent; // @synthesize mmUserAgent=_mmUserAgent;
- (id)networkTimeoutAttributeForAppID:(id)arg1;
- (id)objectForAppID:(id)arg1 andPaths:(id)arg2;
- (void)onResUpdateFinish:(long long)arg1 resType:(unsigned int)arg2 subResType:(unsigned int)arg3;
- (void)onResponseGetAppInfoList:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (_Bool)openUseVConsoleWithAppID:(id)arg1;
- (_Bool)pageIsUseVConsoleForAppID:(id)arg1;
- (id)pageTabAttributesForAppID:(id)arg1 page:(id)arg2;
- (id)pageWindowAttributesForAppID:(id)arg1 page:(id)arg2;
- (void)parseNotifyMsg:(id)arg1;
- (void)saveNotifyStorage:(id)arg1;
- (void)setAppConfigJSON:(id)arg1 forAppID:(id)arg2;
- (void)setContactAttributeWithAppID:(id)arg1 weAppInfo:(id)arg2;
- (void)setDebugModeDownloadPkgCompleteWithAppid:(id)arg1 debugType:(unsigned long long)arg2 value:(_Bool)arg3;
- (id)stringForAppID:(id)arg1 andPaths:(id)arg2;
- (id)systemSetting;
- (void)systemSettingCategoryOnServiceClearData;
- (void)systemSettingCategoryOnServiceInit;
- (void)systemSettingCategoryOnServiceReloadData;
- (void)updateMMUserAgent;
- (void)updateSystemSettingData:(id)arg1;
- (id)waappBanSceneWithAppid:(id)arg1 banScene:(unsigned long long)arg2;
- (id)waappDetailInfoViewURLWithAppid:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

