//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSObject<OS_dispatch_queue>, NSString, NSURLSession, NSURLSessionDownloadTask;

@interface WADownloadFileTask : NSObject
{
    NSString *_appID;
    NSObject<OS_dispatch_queue> *_workerQueue;
    NSMutableSet *_setRequestURL;
    NSURLSession *_urlSession;
    NSURLSessionDownloadTask *_task;
    CDUnknownBlockType _completionHandler;
    id <WADownloadFileTaskDelegate> delegate;
}

- (void).cxx_destruct;
- (_Bool)addRequestURLAndFailIfExist:(id)arg1;
- (id)appID;
- (void)callCompletionHandlerWithLocalID:(id)arg1 statusCode:(long long)arg2 error:(id)arg3;
- (void)cancel;
- (void)dealloc;
@property __weak id <WADownloadFileTaskDelegate> delegate; // @synthesize delegate;
- (id)initWithAppID:(id)arg1 urlSession:(id)arg2 workerQueue:(id)arg3;
- (_Bool)isCachedURL:(id)arg1 getLocalID:(id *)arg2;
- (void)recordDownloadFileURL:(id)arg1 localID:(id)arg2;
- (void)removeRequestURL:(id)arg1;
- (void)setCompletionHandler:(CDUnknownBlockType)arg1;
- (void)startWithURL:(id)arg1 userAgent:(id)arg2 referer:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)taskDidEnd;
- (id)workerQueue;

@end

