//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WADownloadFileTaskDelegate.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString, NSURLSession, WADownloadFileConfig;

@interface WADownloadFileHandler : NSObject <WADownloadFileTaskDelegate>
{
    NSString *_appID;
    NSObject<OS_dispatch_queue> *_workerQueue;
    WADownloadFileConfig *_downloadFileConfig;
    NSMutableArray *_arrDownloadTask;
    NSURLSession *_urlSession;
}

- (void).cxx_destruct;
- (void)cancelAndDeleteAllTask;
- (void)dealloc;
- (void)deleteTask:(id)arg1;
- (void)downloadFileTaskDidEnd:(id)arg1;
- (id)getNewDownloadTask;
- (id)initWithAppID:(id)arg1 appVersion:(unsigned long long)arg2 workerQueue:(id)arg3;
- (void)invalidate;
- (_Bool)isExceedMaxTaskCount;
- (unsigned int)maxTaskCount;
- (void)setupNSURLSession;
- (void)startDownloadTaskWithUrl:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

