//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface WAFavItem : MMObject <PBCoding>
{
    unsigned int favTime;
    unsigned int debugMode;
    NSString *userName;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) unsigned int debugMode; // @synthesize debugMode;
@property(nonatomic) unsigned int favTime; // @synthesize favTime;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (_Bool)isEqualToFavItem:(id)arg1;
@property(copy, nonatomic) NSString *userName; // @synthesize userName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

