//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface WAFloatObject : NSObject
{
    NSString *_content;
    UIColor *_color;
    double _speed;
    double _textWidth;
    struct CGPoint _position;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
- (void)render:(double)arg1;
- (void)reset;
@property(nonatomic) double speed; // @synthesize speed=_speed;
@property(nonatomic) double textWidth; // @synthesize textWidth=_textWidth;
- (_Bool)update:(double)arg1;

@end

