//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "MMWebImageViewDelegate.h"

@class MMUIButton, MMUILabel, MMWebImageView, NSString;

@interface WAHomeGridCell : UICollectionViewCell <MMWebImageViewDelegate>
{
    _Bool _isInEdit;
    _Bool _isInvalid;
    NSString *_appid;
    NSString *_iconUrl;
    NSString *_title;
    unsigned long long _debugMode;
    id <WAHomeCardCellDelegate> _delegate;
    MMWebImageView *_headImageView;
    MMUILabel *_titleLabel;
    MMUIButton *_deleteBtn;
    MMUILabel *_debugLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property(retain, nonatomic) MMUILabel *debugLabel; // @synthesize debugLabel=_debugLabel;
@property(nonatomic) unsigned long long debugMode; // @synthesize debugMode=_debugMode;
@property(nonatomic) __weak id <WAHomeCardCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MMUIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
- (void)deleteButtonDidClick:(id)arg1;
@property(retain, nonatomic) MMWebImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
- (void)initDebugLabel;
- (void)initDeleteBtn;
- (void)initLogoImageView;
- (void)initTitleLabel;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isInEdit; // @synthesize isInEdit=_isInEdit;
@property(nonatomic) _Bool isInvalid; // @synthesize isInvalid=_isInvalid;
- (void)layoutSubviews;
- (void)onLoadImageOK:(id)arg1;
- (void)setIsInEdit:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

