//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class MMBadgeView, NSString, UIImageView, UILabel;

@interface WAHomeSpecialCell : UICollectionViewCell
{
    NSString *_title;
    NSString *_msgString;
    unsigned long long _msgUnreadCount;
    UIImageView *_logoImageView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    MMBadgeView *_badgeView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMBadgeView *badgeView; // @synthesize badgeView=_badgeView;
- (void)configUI;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
- (void)initDetailLabel;
- (void)initLogoImageView;
- (void)initTitleLabel;
- (void)initUnReadView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(copy, nonatomic) NSString *msgString; // @synthesize msgString=_msgString;
@property(nonatomic) unsigned long long msgUnreadCount; // @synthesize msgUnreadCount=_msgUnreadCount;
- (void)prepareForReuse;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

