//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

#import "WAAlertDialogDelegate.h"

@class NSString, WAAlertDialog;

@interface WAJSEventHandler_showModal : WAJSEventHandler_BaseEvent <WAAlertDialogDelegate>
{
    WAAlertDialog *_alertDlg;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WAAlertDialog *alertDlg; // @synthesize alertDlg=_alertDlg;
- (void)handleJSEvent:(id)arg1;
- (void)onCancel;
- (void)onConfirm;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

