//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

@interface WAMapCoverInfo : NSObject
{
    float _rotate;
    id <QAnnotation> _annotation;
    UIImage *_image;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <QAnnotation> annotation; // @synthesize annotation=_annotation;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) float rotate; // @synthesize rotate=_rotate;

@end

