//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSMutableSet, NSString;

@interface WAPermissionMgr : MMService <PBMessageObserverDelegate, MMService>
{
    NSMutableSet *_setDownloadingAppID;
}

+ (id)dictionayOfJSAPI2PermissionIndex;
+ (id)getPermissionByte:(id)arg1;
+ (unsigned int)getPermissionMode:(id)arg1;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)dealloc;
- (_Bool)downloadPermissionBytesWithAppID:(id)arg1;
- (id)getPermissionBytesWithAppID:(id)arg1;
- (id)loadPermissionBytesFromDBWithAppID:(id)arg1;
- (void)onResponsePermissionBytes:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (void)savePermissionBytesToDB:(id)arg1 withAppID:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

