//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WABaseWebViewBanener.h"

@class MMWebImageView, NSString, UIButton, UILabel;

@interface WAQuickAddWebViewBanner : WABaseWebViewBanener
{
    MMWebImageView *m_logoView;
    UILabel *m_tipLabel;
    UIButton *m_addButton;
    id <WAQuickAddWebViewBannerDelegate> _delegate;
    NSString *_userName;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WAQuickAddWebViewBannerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)initAddButton;
- (void)initLogoView;
- (void)initTipLabel;
- (void)layoutSubviews;
- (void)onAdd;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;

@end

