//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURLSession, NSURLSessionTask;

@interface WARequestTask : NSObject
{
    NSString *_appID;
    NSURLSession *_urlSession;
    NSURLSessionTask *_task;
    CDUnknownBlockType _completionHandler;
    id <WARequestTaskDelegate> delegate;
}

- (void).cxx_destruct;
- (void)callCompletionHandlerWithString:(id)arg1 statusCode:(long long)arg2 error:(id)arg3;
- (void)cancel;
- (void)dealloc;
@property __weak id <WARequestTaskDelegate> delegate; // @synthesize delegate;
- (id)initWithAppID:(id)arg1 urlSession:(id)arg2;
- (void)setCompletionHandler:(CDUnknownBlockType)arg1;
- (void)startWithURL:(id)arg1 data:(id)arg2 httpHeaders:(id)arg3 userAgent:(id)arg4 referer:(id)arg5 method:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;

@end

