//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportDestopOpItem : WAReportBaseItem
{
    int _appOldSeq;
    int _appNewSeq;
    unsigned long long _eventTime;
    unsigned long long _opActionType;
    unsigned long long _opScene;
    NSString *_sortSessionId;
}

- (void).cxx_destruct;
@property(nonatomic) int appNewSeq; // @synthesize appNewSeq=_appNewSeq;
@property(nonatomic) int appOldSeq; // @synthesize appOldSeq=_appOldSeq;
@property(nonatomic) unsigned long long eventTime; // @synthesize eventTime=_eventTime;
@property(nonatomic) unsigned long long opActionType; // @synthesize opActionType=_opActionType;
@property(nonatomic) unsigned long long opScene; // @synthesize opScene=_opScene;
- (id)reportString;
@property(copy, nonatomic) NSString *sortSessionId; // @synthesize sortSessionId=_sortSessionId;

@end

