//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAUtility : NSObject
{
}

+ (unsigned int)GenWebviewID;
+ (unsigned long long)currentTimeInMilliseconds;
+ (_Bool)haveChineseChar:(id)arg1;
+ (id)imageFromBase64String:(id)arg1;
+ (void)initWeAppServiceOnEnterEntry;
+ (id)parseURLParams:(id)arg1;

@end

