//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class CADisplayLink, NSMutableArray, NSMutableDictionary;

@interface WAVideoLayer : CALayer
{
    _Bool _playing;
    NSMutableDictionary *_floatList;
    NSMutableArray *_visibleList;
    CADisplayLink *_displayLink;
    double _currentTime;
}

- (void).cxx_destruct;
- (void)addFloat:(id)arg1 color:(id)arg2;
- (void)clearFloat;
@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
- (void)dealloc;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)enableFloat:(_Bool)arg1;
@property(retain, nonatomic) NSMutableDictionary *floatList; // @synthesize floatList=_floatList;
- (void)forceUpdate;
- (double)getRandomY;
- (id)init;
- (void)initFloat:(id)arg1;
- (void)invalidate;
- (void)onUpdateFloat;
@property(nonatomic) _Bool playing; // @synthesize playing=_playing;
@property(retain, nonatomic) NSMutableArray *visibleList; // @synthesize visibleList=_visibleList;
- (void)updateVideoTime:(double)arg1;

@end

