//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

#import "IMMLanguageMgrExt.h"

@class NSString, UIButton, UILabel, UIView, WCAccountTextFieldItem, WCBaseKeyboardToolBar;

@interface WCAccountLoginLastUserViewController : WCAccountBaseViewController <IMMLanguageMgrExt>
{
    WCAccountTextFieldItem *m_textFieldPwdItem;
    WCBaseKeyboardToolBar *m_keyboardBar;
    UIButton *m_loginBtn;
    UIButton *m_switchAccountBtn;
    UIButton *m_voicePrintLoginBtn;
    UILabel *m_labelUserName;
    UIView *m_separatorLine;
    id <WCAccountLoginLastUserViewControllerDelegate> m_delegate;
    NSString *m_nsName;
    _Bool m_bUsePwdForLogin;
}

- (void).cxx_destruct;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)adjustTableViewRect;
- (void)adjustViewAndNavBarRect;
- (id)createFooterBtn:(id)arg1 target:(id)arg2 sel:(SEL)arg3;
- (id)createHeadImgView;
- (void)createLoginBtn:(id)arg1 relateView:(id)arg2;
- (id)createPwdInputView:(id)arg1;
- (id)createVoicePrintLoginBtn:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (id)getDisplayLoginName;
- (double)getVisibleHeight;
- (void)hideKeyBoard;
- (id)init;
- (void)initChangeAccountBtnForIPad;
- (void)initHeaderView;
- (_Bool)isLastLoginAcountTypePhone;
- (void)onLastUserChangeAccountForIPad:(id)arg1;
- (void)onLastUserVoicePrintLogin;
- (void)onMore:(id)arg1;
- (void)onNext;
- (void)onSwitchPwdInput;
- (void)setDelegate:(id)arg1;
- (void)vcResignFirstResponder;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

