//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary, NSString, WCADBodyWrap, WCADCanvasInfo, WCADChainStrengthenInfo, WCADCommentWrap, WCADPageWrap, WCADPoiInfo, WCADVideoWrap, WCAdFeedDisplayInfo, WCMultiLanguageItem;

@interface WCAdvertiseInfo : NSObject <NSCoding>
{
    int adType;
    NSString *adDescription;
    NSString *adActionLink;
    NSString *adActionCardTpId;
    NSString *adActionCardExt;
    NSString *adActionCardTitle;
    int adActionType;
    NSString *adViewId;
    int adPosition;
    int noExposureExpireTime;
    int exposureNoActionExpireTime;
    _Bool webviewRightBarShow;
    NSString *adUserNickName;
    _Bool bExposured;
    int myAdCommentCount;
    unsigned int myAdCommentStartTime;
    NSString *adActionLinkWithTraceId;
    int source;
    NSString *expId;
    _Bool adActionLinkHidden;
    _Bool attachShareLinkHidden;
    _Bool bWithoutAdExp;
    _Bool bIgnoreNewMsgTip;
    _Bool bIgnoreNewLikeMsg;
    _Bool bIgnoreNewCommentMsg;
    _Bool headClickRightBarShow;
    unsigned int headClickType;
    int longVideoAcessType;
    int adActionAppStoreType;
    NSString *adActionLinkName;
    WCMultiLanguageItem *expandOutsideTitle;
    WCMultiLanguageItem *expandInsideTitle;
    NSString *uxInfo;
    NSString *attachShareLinkUrl;
    NSString *attachShareLinkWording;
    unsigned long long commentStartTime;
    unsigned long long commentEndTime;
    unsigned long long unInterestStartTime;
    unsigned long long unInterestEndTime;
    NSMutableDictionary *adArgsDic;
    NSString *headClickParam;
    WCADPoiInfo *adPoiInfo;
    WCADChainStrengthenInfo *adChainStrengthenInfo;
    NSString *adActionAppStoreTitle;
    NSString *adActionAppStoreLink;
    WCADCanvasInfo *adCanvasInfo;
    NSString *traceId;
    NSString *sessionAid;
    WCAdFeedDisplayInfo *adFeedDisplayInfo;
    WCADBodyWrap *_bodyWrap;
    WCADCommentWrap *_commentWrap;
    WCADPageWrap *_detailPageWrap;
    WCADPageWrap *_h5PageWrap;
    WCADPageWrap *_albumPageWrap;
    WCADVideoWrap *_videoWrap;
    WCADVideoWrap *_streamVideoWrap;
    WCADPageWrap *_poiH5PageWrap;
    NSString *_originUxInfo;
    NSString *_originSnsId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *adActionAppStoreLink; // @synthesize adActionAppStoreLink;
@property(retain, nonatomic) NSString *adActionAppStoreTitle; // @synthesize adActionAppStoreTitle;
@property(nonatomic) int adActionAppStoreType; // @synthesize adActionAppStoreType;
@property(retain, nonatomic) NSString *adActionCardExt; // @synthesize adActionCardExt;
@property(retain, nonatomic) NSString *adActionCardTitle; // @synthesize adActionCardTitle;
@property(retain, nonatomic) NSString *adActionCardTpId; // @synthesize adActionCardTpId;
@property(retain, nonatomic) NSString *adActionLink; // @synthesize adActionLink;
@property(nonatomic) _Bool adActionLinkHidden; // @synthesize adActionLinkHidden;
@property(retain, nonatomic) NSString *adActionLinkName; // @synthesize adActionLinkName;
@property(retain, nonatomic) NSString *adActionLinkWithTraceId; // @synthesize adActionLinkWithTraceId;
@property(nonatomic) int adActionType; // @synthesize adActionType;
@property(retain, nonatomic) NSMutableDictionary *adArgsDic; // @synthesize adArgsDic;
@property(retain, nonatomic) WCADCanvasInfo *adCanvasInfo; // @synthesize adCanvasInfo;
@property(retain, nonatomic) WCADChainStrengthenInfo *adChainStrengthenInfo; // @synthesize adChainStrengthenInfo;
@property(retain, nonatomic) NSString *adDescription; // @synthesize adDescription;
@property(retain, nonatomic) WCAdFeedDisplayInfo *adFeedDisplayInfo; // @synthesize adFeedDisplayInfo;
@property(retain, nonatomic) WCADPoiInfo *adPoiInfo; // @synthesize adPoiInfo;
@property(nonatomic) int adPosition; // @synthesize adPosition;
@property(nonatomic) int adType; // @synthesize adType;
@property(retain, nonatomic) NSString *adUserNickName; // @synthesize adUserNickName;
@property(retain, nonatomic) NSString *adViewId; // @synthesize adViewId;
@property(retain, nonatomic) WCADPageWrap *albumPageWrap; // @synthesize albumPageWrap=_albumPageWrap;
@property(nonatomic) _Bool attachShareLinkHidden; // @synthesize attachShareLinkHidden;
@property(retain, nonatomic) NSString *attachShareLinkUrl; // @synthesize attachShareLinkUrl;
@property(retain, nonatomic) NSString *attachShareLinkWording; // @synthesize attachShareLinkWording;
@property(nonatomic) _Bool bExposured; // @synthesize bExposured;
@property(nonatomic) _Bool bIgnoreNewCommentMsg; // @synthesize bIgnoreNewCommentMsg;
@property(nonatomic) _Bool bIgnoreNewLikeMsg; // @synthesize bIgnoreNewLikeMsg;
@property(nonatomic) _Bool bIgnoreNewMsgTip; // @synthesize bIgnoreNewMsgTip;
@property(nonatomic) _Bool bWithoutAdExp; // @synthesize bWithoutAdExp;
@property(retain, nonatomic) WCADBodyWrap *bodyWrap; // @synthesize bodyWrap=_bodyWrap;
@property(nonatomic) unsigned long long commentEndTime; // @synthesize commentEndTime;
@property(nonatomic) unsigned long long commentStartTime; // @synthesize commentStartTime;
@property(retain, nonatomic) WCADCommentWrap *commentWrap; // @synthesize commentWrap=_commentWrap;
- (long long)countOfAdCanvasPageList;
@property(retain, nonatomic) WCADPageWrap *detailPageWrap; // @synthesize detailPageWrap=_detailPageWrap;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSString *expId; // @synthesize expId;
@property(retain, nonatomic) WCMultiLanguageItem *expandInsideTitle; // @synthesize expandInsideTitle;
@property(retain, nonatomic) WCMultiLanguageItem *expandOutsideTitle; // @synthesize expandOutsideTitle;
@property(nonatomic) int exposureNoActionExpireTime; // @synthesize exposureNoActionExpireTime;
- (id)genAdStatExt:(_Bool)arg1;
- (id)getAdActionLink;
- (id)getAdActionTitle;
- (unsigned int)getAdClickLinkActionType;
@property(retain, nonatomic) WCADPageWrap *h5PageWrap; // @synthesize h5PageWrap=_h5PageWrap;
- (_Bool)hasMyAdComments;
@property(retain, nonatomic) NSString *headClickParam; // @synthesize headClickParam;
@property(nonatomic) _Bool headClickRightBarShow; // @synthesize headClickRightBarShow;
@property(nonatomic) unsigned int headClickType; // @synthesize headClickType;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (_Bool)isAppstoreInternalJump;
- (_Bool)isCanvasAd;
- (_Bool)isVaildForShow;
- (_Bool)isValidForJumpAppstore;
@property(nonatomic) int longVideoAcessType; // @synthesize longVideoAcessType;
@property(nonatomic) int myAdCommentCount; // @synthesize myAdCommentCount;
@property(nonatomic) unsigned int myAdCommentStartTime; // @synthesize myAdCommentStartTime;
@property(nonatomic) int noExposureExpireTime; // @synthesize noExposureExpireTime;
@property(retain, nonatomic) NSString *originSnsId; // @synthesize originSnsId=_originSnsId;
@property(retain, nonatomic) NSString *originUxInfo; // @synthesize originUxInfo=_originUxInfo;
@property(retain, nonatomic) WCADPageWrap *poiH5PageWrap; // @synthesize poiH5PageWrap=_poiH5PageWrap;
@property(retain, nonatomic) NSString *sessionAid; // @synthesize sessionAid;
@property(nonatomic) int source; // @synthesize source;
@property(retain, nonatomic) WCADVideoWrap *streamVideoWrap; // @synthesize streamVideoWrap=_streamVideoWrap;
@property(retain, nonatomic) NSString *traceId; // @synthesize traceId;
@property(nonatomic) unsigned long long unInterestEndTime; // @synthesize unInterestEndTime;
@property(nonatomic) unsigned long long unInterestStartTime; // @synthesize unInterestStartTime;
@property(retain, nonatomic) NSString *uxInfo; // @synthesize uxInfo;
@property(retain, nonatomic) WCADVideoWrap *videoWrap; // @synthesize videoWrap=_videoWrap;
@property(nonatomic) _Bool webviewRightBarShow; // @synthesize webviewRightBarShow;

@end

