//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CdnComVideoProcessInfo, CdnDownloadTaskInfo, CdnProgressInfo;

@protocol WCAVPlayerDataMrgExt <NSObject>

@optional
- (void)OnCdnDownloadVideoFail:(CdnDownloadTaskInfo *)arg1;
- (void)OnCdnDownloadVideoSuccess:(CdnDownloadTaskInfo *)arg1;
- (void)notifyToNeedCheckPlayState:(CdnComVideoProcessInfo *)arg1;
- (void)onDownloadToEnd:(CdnComVideoProcessInfo *)arg1;
- (void)onRecievedAVData:(CdnComVideoProcessInfo *)arg1 NeedNotifyToPlay:(_Bool)arg2;
- (void)onRecievedAVData:(CdnProgressInfo *)arg1 offset:(unsigned long long)arg2;
- (void)onRecievedFristPartAVData:(CdnComVideoProcessInfo *)arg1;
@end

