//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class NSString, WCCardDataCardInfo, WCCardDataCardTPInfo;

@interface WCCardTicketCardView : MMUIView
{
    id <WCCardTicketCardViewDelegate> _delegate;
    WCCardDataCardInfo *_cardInfo;
    WCCardDataCardTPInfo *_cardTPInfo;
    NSString *_cardStatusTitle;
    double _contentHeight;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCCardDataCardInfo *cardInfo; // @synthesize cardInfo=_cardInfo;
@property(retain, nonatomic) NSString *cardStatusTitle; // @synthesize cardStatusTitle=_cardStatusTitle;
@property(retain, nonatomic) WCCardDataCardTPInfo *cardTPInfo; // @synthesize cardTPInfo=_cardTPInfo;
@property(nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
@property(nonatomic) __weak id <WCCardTicketCardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (double)getContentViewRealHeight;
- (id)initTicketCardViewWithFrame:(struct CGRect)arg1 withCardInfo:(id)arg2 withCardTpInfo:(id)arg3 withCardStatusTitle:(id)arg4;
- (void)initView;
- (void)onClickApplyBtn:(id)arg1;

@end

