//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface WCCardFieldItem : MMObject <PBCoding>
{
    unsigned int showflag;
    NSString *title;
    NSString *subTitle;
    NSString *auxTitle;
    NSString *url;
    NSString *primaryColor;
    NSString *secondaryColor;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *auxTitle; // @synthesize auxTitle;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(retain, nonatomic) NSString *primaryColor; // @synthesize primaryColor;
@property(retain, nonatomic) NSString *secondaryColor; // @synthesize secondaryColor;
@property(nonatomic) unsigned int showflag; // @synthesize showflag;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSString *url; // @synthesize url;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

