//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCoding.h"

@class NSArray, NSDictionary;

@protocol WCDBCoding <PBCoding>
+ (id)dummyObject;
+ (const map_7a576766 *)getValueNameIndexMap;
+ (NSArray *)getValueTable;
@property(nonatomic) long long __rowID;

@optional
+ (const map_0e718273 *)getFileValueTagIndexMap;
+ (NSArray *)getFileValueTypeTable;
+ (const map_0e718273 *)getPackedValueTagIndexMap;
+ (NSArray *)getPackedValueTypeTable;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (NSDictionary *)getWCDBTableHelperDictionary;
@end

