//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCDBConfigCheckpoint : NSObject
{
    _Bool m_integrity;
    _Bool m_skipMainThread;
    _Bool m_keepIndexRecover;
    int m_failedLimit;
    int m_frame;
}

+ (void)initialize;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(nonatomic) int m_failedLimit; // @synthesize m_failedLimit;
@property(nonatomic) int m_frame; // @synthesize m_frame;
@property(nonatomic) _Bool m_integrity; // @synthesize m_integrity;
@property(nonatomic) _Bool m_keepIndexRecover; // @synthesize m_keepIndexRecover;
@property(nonatomic) _Bool m_skipMainThread; // @synthesize m_skipMainThread;

@end

