//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "FavAddItemHelperDelegate.h"
#import "ForwardMessageLogicDelegate.h"
#import "IVOIPUILogicMgrExt.h"
#import "MMExposeViewControllerDelegate.h"
#import "ShareDataToOpenSDKControllerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WCImageFullScreenViewContainerDelegate.h"
#import "WCShareAuthViewControllerExt.h"
#import "scrollViewDelegate.h"

@class ForwardMessageLogicController, MMScrollView, NSArray, NSMutableArray, NSString, ShareDataToOpenSDKController, UIPageControl, UIView;

@interface WCImageFullScreenViewController : MMUIViewController <UIScrollViewDelegate, scrollViewDelegate, WCImageFullScreenViewContainerDelegate, IVOIPUILogicMgrExt, MMExposeViewControllerDelegate, ShareDataToOpenSDKControllerDelegate, FavAddItemHelperDelegate, ForwardMessageLogicDelegate, WCShareAuthViewControllerExt>
{
    UIView *m_fakeScreenView;
    struct CGRect m_originImageRectInScreen;
    _Bool m_isAnimating;
    MMScrollView *m_scrollView;
    UIPageControl *m_pageCtrl;
    UIView *m_blackMask;
    NSArray *m_arrMediaDataWrap;
    NSArray *m_arrMediaData;
    NSMutableArray *m_arrImage;
    unsigned int m_iCurIndex;
    _Bool m_hasScroll;
    long long m_lastDeviceOrientation;
    _Bool m_isAnimationShowing;
    _Bool m_isRotating;
    _Bool m_forbidPreloadImg;
    ShareDataToOpenSDKController *m_shareDataToOpenSDKController;
    ForwardMessageLogicController *m_forwardMsgLogic;
    unsigned int _startTime;
    id <WCImageFullScreenViewControllerDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (void)animationHideStop;
- (void)animationHideWithRotate;
- (void)animationShowWithHint:(id)arg1;
- (void)animationShowWithMediaDataArray:(id)arg1 mediaDataWrapArray:(id)arg2 originView:(id)arg3 index:(unsigned int)arg4;
- (void)animationShowWithMediaDataArray:(id)arg1 originView:(id)arg2 index:(unsigned int)arg3;
- (void)captureScreen;
- (void)clearStatus;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)downloadImage;
- (id)getCurMediaItemWrap;
- (id)getCurrentViewController;
- (id)getVisibleViewController;
- (void)hideWithoutAnimation;
- (_Bool)isContainerVisible:(id)arg1;
@property(nonatomic) __weak id <WCImageFullScreenViewControllerDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) unsigned int m_iCurIndex; // @synthesize m_iCurIndex;
- (void)onAddFavTagBegin;
- (void)onAddFavTagEnd;
- (void)onAnimateFadeOut;
- (void)onContainerAnimationHideStart;
- (void)onContainerAnimationHideStop;
- (void)onContainerAnimationShowStart;
- (void)onContainerAnimationShowStop;
- (void)onExposeCancel;
- (void)onExposeComplete;
- (void)onExposeWithDataItem:(id)arg1;
- (id)onGetViewController;
- (void)onLongPressedAddFav:(id)arg1;
- (void)onLongPressedWithMediaItem:(id)arg1;
- (void)onPushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)onShareDataToOpenSDKCancel;
- (void)onShareToOpenSDKWithDataItem:(id)arg1 mediaItem:(id)arg2;
- (void)onTopBarFrameChanged;
- (void)onTryHideWCImageFullScreen;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)resetScrollView;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)shouldHideContainerOnRotate;
- (_Bool)shouldRotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)touchesEnded_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)windowNeed2Hide;
- (void)windowNeed2Show;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

