//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMFullScreenViewController.h"

#import "IMMAssetExt.h"
#import "PageScrollViewDataSource.h"
#import "PageScrollViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class NSMutableArray, NSMutableSet, NSString, PageScrollView, UIButton;

@interface WCMultiImageScannerController : MMFullScreenViewController <IMMAssetExt, UIScrollViewDelegate, PageScrollViewDelegate, PageScrollViewDataSource, WCActionSheetDelegate>
{
    PageScrollView *_pageScrollView;
    UIButton *_deleteButton;
    NSMutableArray *_arrViewItem;
    unsigned long long _currentIndex;
    _Bool _isComeFromRotate;
    _Bool m_bAnimating;
    id <WCMultiImageScannerDelegate> _scannerDelegate;
    NSMutableSet *_setPreviewItem;
}

- (void).cxx_destruct;
- (void)OnMMUIHookViewFrameChanged:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSMutableArray *arrViewItem; // @synthesize arrViewItem=_arrViewItem;
- (struct CGPoint)contentOffsetForPageScrollView;
- (struct CGSize)contentSizeForPageScrollView;
- (unsigned long long)currentIndex:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
- (void)deleteCurrentItem;
- (struct CGRect)frameForPageAtItem:(unsigned long long)arg1;
- (struct CGRect)frameForPageScrollView;
- (void)handleSingleTap;
- (void)hideFullScreen;
- (void)initNavigationBar;
- (void)initScrollView;
- (id)initWithViewItems:(id)arg1 currentIndex:(unsigned long long)arg2;
- (_Bool)interactivePopGestureRecognizerShouldBegin:(id)arg1;
- (unsigned long long)numberOfItems:(id)arg1;
- (void)onAnimationDidStop;
- (void)onAssetImageUpdate:(id)arg1 forKey:(id)arg2;
- (void)onChangedWithCurrentIndex:(long long)arg1;
- (void)onMainWindowFrameChanged;
- (void)onSingleClicked;
- (void)onTopBarFrameChanged;
@property(retain, nonatomic) PageScrollView *pageScrollView; // @synthesize pageScrollView=_pageScrollView;
- (id)pageScrollView:(id)arg1 viewForItem:(unsigned long long)arg2;
@property(nonatomic) __weak id <WCMultiImageScannerDelegate> scannerDelegate; // @synthesize scannerDelegate=_scannerDelegate;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showAlert:(id)arg1;
- (void)showFullScreen;
- (void)showFullScreenAnimated:(_Bool)arg1;
- (void)updateTitle;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

