//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"

@class NSString, RichTextView, UIButton, UILabel, UIScrollView, UISwitch, UIView, WCPayEntrustPayInfo, WCPayOrderDetail;

@interface WCPayAutoDeductSettingViewController : WCPayBaseViewController <ILinkEventExt>
{
    id <WCPayAutoDeductSettingViewControllerDelegate> m_delegate;
    UIView *_backgroundView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UILabel *_feeTypeLabel;
    UILabel *_feeLabel;
    UILabel *_contractTitleLabel;
    UISwitch *_switchButton;
    UIView *_titleTopLine;
    UIView *_titleBottomLine;
    UIView *_showInfoView;
    double _showInfoHeight;
    UIView *_backgroundBottomLine;
    UIButton *_footerButton;
    RichTextView *_richTextView;
    WCPayOrderDetail *_order;
    WCPayEntrustPayInfo *_entrustPayInfo;
    UIScrollView *_scrollView;
}

- (void).cxx_destruct;
- (void)OnCancel;
- (void)OnFooterButtonClick:(id)arg1;
@property(retain, nonatomic) UIView *backgroundBottomLine; // @synthesize backgroundBottomLine=_backgroundBottomLine;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)changeSwitch:(id)arg1;
@property(retain, nonatomic) UILabel *contractTitleLabel; // @synthesize contractTitleLabel=_contractTitleLabel;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) WCPayEntrustPayInfo *entrustPayInfo; // @synthesize entrustPayInfo=_entrustPayInfo;
@property(retain, nonatomic) UILabel *feeLabel; // @synthesize feeLabel=_feeLabel;
@property(retain, nonatomic) UILabel *feeTypeLabel; // @synthesize feeTypeLabel=_feeTypeLabel;
@property(retain, nonatomic) UIButton *footerButton; // @synthesize footerButton=_footerButton;
- (id)getShowInfoView:(id)arg1;
- (void)initNavigationBar;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
@property(retain, nonatomic) WCPayOrderDetail *order; // @synthesize order=_order;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)setDelegate:(id)arg1;
@property(nonatomic) double showInfoHeight; // @synthesize showInfoHeight=_showInfoHeight;
@property(retain, nonatomic) UIView *showInfoView; // @synthesize showInfoView=_showInfoView;
@property(retain, nonatomic) UISwitch *switchButton; // @synthesize switchButton=_switchButton;
@property(retain, nonatomic) UIView *titleBottomLine; // @synthesize titleBottomLine=_titleBottomLine;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *titleTopLine; // @synthesize titleTopLine=_titleTopLine;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

