//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCBizBaseViewController.h"

#import "MMWebViewDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WCPayCommentTextViewDelegate.h"
#import "WCPayCurrencyInputViewDelegate.h"
#import "WCPayNoticeBannerViewDelegate.h"
#import "WCPayOverseaTransferGetCurrencyCgiDelegate.h"
#import "WCPayOverseaTransferOrderCgiDelegate.h"

@class MMHeadImageView, NSDictionary, NSString, UIButton, UILabel, UIScrollView, UIView, WCBizLoadingView, WCPayCommentTextView, WCPayCurrencyInputView, WCPayNoticeBannerView, WCPayOverseaTransferGetCurrencyCgi, WCPayOverseaTransferGetCurrencyCgiRespObject, WCPayOverseaTransferOrderCgi, WCPayOverseaTransferOrderResp;

@interface WCPayOverseaTransferViewController : WCBizBaseViewController <WCPayCurrencyInputViewDelegate, WCPayCommentTextViewDelegate, WCPayOverseaTransferGetCurrencyCgiDelegate, WCPayOverseaTransferOrderCgiDelegate, MMWebViewDelegate, UIScrollViewDelegate, WCPayNoticeBannerViewDelegate>
{
    int _m_walletType;
    NSString *_m_username;
    UIScrollView *_m_scrollView;
    UIView *_m_headerView;
    MMHeadImageView *_m_headImageView;
    UILabel *_m_displayNameLabel;
    UIView *_m_panelView;
    UILabel *_m_inputTitleLabel;
    WCPayCurrencyInputView *_m_currencyInputView;
    UIView *_m_lineView;
    WCPayCommentTextView *_m_commentTextView;
    UIView *_m_footerView;
    UIButton *_m_confirmButton;
    WCPayNoticeBannerView *_m_noticeBannerView;
    WCBizLoadingView *_m_bizLoadingView;
    WCPayOverseaTransferGetCurrencyCgi *_m_getCurrencyCgi;
    WCPayOverseaTransferOrderCgi *_m_orderCgi;
    WCPayOverseaTransferGetCurrencyCgiRespObject *_m_currencyResp;
    WCPayOverseaTransferOrderResp *_m_orderResp;
    NSDictionary *_m_payResp;
}

- (void).cxx_destruct;
- (void)delayDismissMySelf;
- (void)didReceiveMemoryWarning;
- (void)initView;
- (id)initWithUsername:(id)arg1 WalletType:(int)arg2;
@property(retain, nonatomic) WCBizLoadingView *m_bizLoadingView; // @synthesize m_bizLoadingView=_m_bizLoadingView;
@property(retain, nonatomic) WCPayCommentTextView *m_commentTextView; // @synthesize m_commentTextView=_m_commentTextView;
@property(retain, nonatomic) UIButton *m_confirmButton; // @synthesize m_confirmButton=_m_confirmButton;
@property(retain, nonatomic) WCPayCurrencyInputView *m_currencyInputView; // @synthesize m_currencyInputView=_m_currencyInputView;
@property(retain, nonatomic) WCPayOverseaTransferGetCurrencyCgiRespObject *m_currencyResp; // @synthesize m_currencyResp=_m_currencyResp;
@property(retain, nonatomic) UILabel *m_displayNameLabel; // @synthesize m_displayNameLabel=_m_displayNameLabel;
@property(retain, nonatomic) UIView *m_footerView; // @synthesize m_footerView=_m_footerView;
@property(retain, nonatomic) WCPayOverseaTransferGetCurrencyCgi *m_getCurrencyCgi; // @synthesize m_getCurrencyCgi=_m_getCurrencyCgi;
@property(retain, nonatomic) MMHeadImageView *m_headImageView; // @synthesize m_headImageView=_m_headImageView;
@property(retain, nonatomic) UIView *m_headerView; // @synthesize m_headerView=_m_headerView;
@property(retain, nonatomic) UILabel *m_inputTitleLabel; // @synthesize m_inputTitleLabel=_m_inputTitleLabel;
@property(retain, nonatomic) UIView *m_lineView; // @synthesize m_lineView=_m_lineView;
@property(retain, nonatomic) WCPayNoticeBannerView *m_noticeBannerView; // @synthesize m_noticeBannerView=_m_noticeBannerView;
@property(retain, nonatomic) WCPayOverseaTransferOrderCgi *m_orderCgi; // @synthesize m_orderCgi=_m_orderCgi;
@property(retain, nonatomic) WCPayOverseaTransferOrderResp *m_orderResp; // @synthesize m_orderResp=_m_orderResp;
@property(retain, nonatomic) UIView *m_panelView; // @synthesize m_panelView=_m_panelView;
@property(retain, nonatomic) NSDictionary *m_payResp; // @synthesize m_payResp=_m_payResp;
@property(retain, nonatomic) UIScrollView *m_scrollView; // @synthesize m_scrollView=_m_scrollView;
@property(retain, nonatomic) NSString *m_username; // @synthesize m_username=_m_username;
@property(nonatomic) int m_walletType; // @synthesize m_walletType=_m_walletType;
- (void)onBack;
- (void)onButtonConfirm;
- (void)onClickContinueTransfer;
- (void)onClickOpenTradeUrl;
- (void)onInputTextChangeToString:(id)arg1;
- (void)onWCPayCommentTextViewAlertViewAppear;
- (void)onWCPayCommentTextViewAlertViewDisappear;
- (void)onWCPayNoticeBannerView:(id)arg1 clickWithUrl:(id)arg2;
- (void)onWCPayOverseaTransferGetCurrencyBizErrorWithRetCode:(int)arg1 ErrorMsg:(id)arg2;
- (void)onWCPayOverseaTransferGetCurrencyCgiErrorWithRetCode:(int)arg1 ErrorMsg:(id)arg2;
- (void)onWCPayOverseaTransferGetCurrencyCgiOkArgument:(id)arg1;
- (void)onWCPayOverseaTransferOrderBizErrorWithRetCode:(int)arg1 ErrorMsg:(id)arg2;
- (void)onWCPayOverseaTransferOrderCgiErrorWithRetCode:(int)arg1 ErrorMsg:(id)arg2;
- (void)onWCPayOverseaTransferOrderCgiOkWithResp:(id)arg1;
- (void)onWCPayOverseaTransferOrderCgiRetrunHasUnreceiveTransferWithResp:(id)arg1;
- (void)onWCPayOverseaTransferOrderCgiReturnHasTheSameAmountUnreceiveTransferWithResp:(id)arg1;
- (void)onWebViewWillClose:(id)arg1;
- (void)reportCancel;
- (void)reportConfirm;
- (void)reportIdKeyOverseaTransferViewOpen;
- (void)reportIdkeyOverseaTransferCancel;
- (void)reportIdkeyOverseaTransferConfirm;
- (void)reportIdkeyOverseaTransferGetCurrencyFailed;
- (void)reportIdkeyOverseaTransferGetCurrencyOk;
- (void)reportIdkeyOverseaTransferGetCurrencyOkChangeToRMB;
- (void)reportIdkeyOverseaTransferGetCurrencyOkContinue;
- (void)reportIdkeyOverseaTransferOrderFailed;
- (void)reportIdkeyOverseaTransferOrderOk;
- (void)reportOverseaTransferEnter;
- (void)scrollViewDidScroll:(id)arg1;
- (void)startBizLoading;
- (void)stopBizLoading;
- (id)trimString:(id)arg1 ToLenght:(unsigned long long)arg2;
- (void)updateBizLoadingView;
- (void)updateCommentTextView;
- (void)updateConfirmButton;
- (void)updateConfirmButtonStatus;
- (void)updateCurrencyInputView;
- (void)updateDisplayNameLabel;
- (void)updateFooterView;
- (void)updateHeadImageView;
- (void)updateHeaderView;
- (void)updateInputTitleLabel;
- (void)updateLineView;
- (void)updateNoticeBannerView;
- (void)updatePanelView;
- (void)updateScrollView;
- (void)updateViewData;
- (void)viewDidBePresented:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)webViewReturn:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

