//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class UIView;

@interface WCPayOverseaMainWalletFooterView : UICollectionReusableView
{
    UIView *_m_coverView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
@property(retain, nonatomic) UIView *m_coverView; // @synthesize m_coverView=_m_coverView;
- (void)updateCoverView;

@end

