//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "PBMessageObserverDelegate.h"
#import "WCPayGPOrderHistoryControllerDelegate.h"

@class NSString;

@interface WCPayGPOrderHistoryControlLogic : WCPayControlLogic <PBMessageObserverDelegate, WCPayGPOrderHistoryControllerDelegate>
{
}

- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)dealloc;
- (id)initWithData:(id)arg1;
- (void)loadMoreOrderHistoryWithOffset:(unsigned int)arg1;
- (void)onGetGroupPayOrderHistory:(id)arg1;
- (void)onOrderHistoryViewControllerCancel;
- (void)onOrderHistoryViewControllerUserSelectRecord:(id)arg1;
- (void)queryLaunchOrderHistoryWithOffset:(unsigned int)arg1;
- (void)startLogic;
- (void)stopLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

