//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableDictionary, NSString, WCPayTradeFavInfo;

@interface WCPayCouponsLogicMgr : MMService <MMService>
{
    WCPayTradeFavInfo *m_oWCPayTradeFavInfo;
    NSMutableDictionary *m_dicFavorItemInComponseInfo;
}

- (void).cxx_destruct;
- (id)AutoAdjustCouponsInfoForSelectedCard:(id)arg1 BalanceBankType:(id)arg2;
- (void)ClearBankFavorInfo;
- (id)DeselectTradeFavItem:(id)arg1;
- (id)GetBankFavorItemAndCouponsInfo;
- (id)GetWCPayTradeFavInfo;
- (id)ResetComposeInfo:(id)arg1;
- (void)ResetTradeFavInfo:(id)arg1;
- (id)SelectTradeFavItem:(id)arg1;
- (void)autoChangeTradeFavorItemStatusToAdjustConpons;
- (void)dealloc;
- (void)onServiceClearData;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceTerminate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

