//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCRedEnvelopesBaseViewController.h"

#import "ILinkEventExt.h"
#import "MMTableViewInfoDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"
#import "WCPayNoticeBannerDelegate.h"

@class MMTextView, NSString, RichTextView, UIButton, UILabel, UIView, WCBaseKeyboardToolBar, WCPayNoticeBanner, WCUITextField;

@interface WCRedEnvelopesMakeRedEnvelopesViewController : WCRedEnvelopesBaseViewController <WCPayNoticeBannerDelegate, UITextFieldDelegate, UITextViewDelegate, ILinkEventExt, MMTableViewInfoDelegate>
{
    id <WCRedEnvelopesMakeRedEnvelopesViewControllerDelegate> m_delegate;
    int m_enMakeRedEnvelopesScene;
    WCUITextField *m_oSelectCountTextField;
    unsigned int m_uiSelectCount;
    UILabel *moneyLabel;
    UILabel *nsDefaultWishingLabel;
    WCUITextField *m_oMoneyTextField;
    MMTextView *m_textView;
    UIButton *normalRedEnvelopesButton;
    WCBaseKeyboardToolBar *m_keyboardBar;
    _Bool m_bDidBack;
    _Bool m_bCanHandleScrollViewDidChangedEvent;
    _Bool m_bNomalMoney;
    RichTextView *richTextView;
    UIView *m_oErrorView;
    UILabel *m_oErrorLabel;
    _Bool m_bError;
    _Bool m_bWaitFiveMintes;
    UIView *oCountSelectView;
    UIView *oSimpleMoneyView;
    long long m_inputErrorType;
    WCPayNoticeBanner *_banner;
}

- (void).cxx_destruct;
- (void)OnClickTailActivity;
- (void)OnLeftBarButtonDone;
- (void)OnMakeWCRedEnvelopesButtonClick;
- (void)OnRightBarButtonClick;
- (void)SetErrorTips;
- (void)SetLeftBarButtonClose;
- (void)adjustMoneyLabel;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
@property(retain, nonatomic) WCPayNoticeBanner *banner; // @synthesize banner=_banner;
- (void)banner:(id)arg1 clickWithUrl:(id)arg2;
- (void)checkDataError;
- (void)checkNextButtonStatus;
- (void)dealloc;
- (void)handleTap:(id)arg1;
- (void)hideErrorView;
- (void)hideErrorViewWithAnimation;
- (void)initData;
- (void)initErrorView;
- (void)initNavigationBar;
@property(nonatomic) int m_enMakeRedEnvelopesScene; // @synthesize m_enMakeRedEnvelopesScene;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)refreshButtonFiveMintes;
- (void)refreshViewWithData:(id)arg1;
- (void)reloadContentView;
- (void)resetToCanHandleScrollViewChangedEnvent;
- (void)setButtonWaitFiveMin;
- (void)setDelegate:(id)arg1;
- (void)showErrorView:(id)arg1 ErrorType:(long long)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidChanged:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidEndOnExit:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (_Bool)useTransparentNavibar;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

