//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCShareCardBaseHeaderView.h"

@class MMUIView;

@interface WCShareCardMemberHeaderView : WCShareCardBaseHeaderView
{
    id <WCShareCardMemberCardHeaderDelegate> _delegate;
    MMUIView *_cardContentView;
}

- (void).cxx_destruct;
- (void)addSecondaryField;
- (_Bool)bIsCardPreAccept;
@property(retain, nonatomic) MMUIView *cardContentView; // @synthesize cardContentView=_cardContentView;
@property(nonatomic) __weak id <WCShareCardMemberCardHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fieldClicked:(id)arg1;
- (id)getLogoName;
- (double)getRealHeight;
- (void)initMemberCardContentViewWithStartY:(double)arg1;
- (void)initView;
- (id)initWithViewWidth:(double)arg1 withCardSourceData:(id)arg2 isShareCard:(_Bool)arg3 cardStatus:(int)arg4 isNeedHideAcceptBtn:(_Bool)arg5 delegate:(id)arg6;
- (id)insertSpaceChar:(id)arg1 hasTransline:(_Bool)arg2;
- (void)onClickApplyBtn:(id)arg1;
- (void)onclickAnnounce:(id)arg1;

@end

