//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "PBMessageObserverDelegate.h"

@class NSString, UIView;

@interface WCShareAuthViewController : MMUIViewController <PBMessageObserverDelegate>
{
    int _type;
    unsigned int _msgType;
    id <WCShareAuthViewControllerDelegate> _delegate;
    NSString *_appName;
    NSString *_appId;
    NSString *_bundleId;
    NSString *_extText;
    NSString *_extUrl;
    UIView *_scrollView;
    UIView *_errView;
    NSString *_errString;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *bundleId; // @synthesize bundleId=_bundleId;
- (void)dealloc;
@property(nonatomic) __weak id <WCShareAuthViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFail;
- (void)didSuccess:(id)arg1;
@property(retain, nonatomic) NSString *errString; // @synthesize errString=_errString;
@property(retain, nonatomic) UIView *errView; // @synthesize errView=_errView;
@property(retain, nonatomic) NSString *extText; // @synthesize extText=_extText;
@property(retain, nonatomic) NSString *extUrl; // @synthesize extUrl=_extUrl;
- (id)getType;
- (void)goBack;
- (id)initWithType:(int)arg1 appid:(id)arg2 bundleId:(id)arg3 txt:(id)arg4 url:(id)arg5 msgType:(unsigned int)arg6;
- (id)makeLink;
@property(nonatomic) unsigned int msgType; // @synthesize msgType=_msgType;
- (void)onBackBtnClick:(id)arg1;
@property(retain, nonatomic) UIView *scrollView; // @synthesize scrollView=_scrollView;
- (void)sendAuthRequest;
@property(nonatomic) int type; // @synthesize type=_type;
- (void)viewDidLoad;

@end

