//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "FTSJSEventDelegate.h"
#import "FTSWebSearchDataSource.h"
#import "UIScrollViewDelegate.h"

@class NSString, UIView, WSResultViewLogic, WebSearchView;

@interface WSLocalWebViewController : MMUIViewController <UIScrollViewDelegate, FTSJSEventDelegate, FTSWebSearchDataSource>
{
    UIView *_navBarBkg;
    WebSearchView *_webView;
    WSResultViewLogic *_resultViewLogic;
    NSString *_contentTitle;
    unsigned long long _businessType;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long businessType; // @synthesize businessType=_businessType;
- (id)init;
- (void)initContentView;
- (void)initNavigationBar;
- (void)initTitleView;
- (void)loadLocalWebView;
- (void)onLaunchPage:(id)arg1 withParams:(id)arg2;
- (void)onOpenBrandContact:(id)arg1 withParams:(id)arg2;
- (void)onOpenContact:(id)arg1;
- (void)onOpenMsgSession:(id)arg1;
- (void)onSearchInputChanged:(id)arg1;
- (_Bool)useTransparentNavibar;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

