//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WWKApi : NSObject
{
}

+ (id)getApiVersion;
+ (id)getAppInstallUrl;
+ (_Bool)handleOpenURL:(id)arg1 delegate:(id)arg2;
+ (_Bool)isAppInstalled;
+ (_Bool)openApp;
+ (_Bool)registerApp:(id)arg1;
+ (_Bool)registerApp:(id)arg1 withDescription:(id)arg2;
+ (_Bool)sendObj:(id)arg1;
+ (_Bool)sendReq:(id)arg1;
+ (_Bool)sendResp:(id)arg1;

@end

