//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WXGBackupPersistentMgr : NSObject
{
}

+ (unsigned long long)checkRecoverState;
+ (void)clearBackupPath;
+ (void)clearBackupTmpData;
+ (void)clearBufferData;
+ (void)deleteSelection;
+ (id)getBackupBufferPath;
+ (id)getBackupIndexDataBasePath;
+ (id)getBackupPath;
+ (id)getBackupReportPath;
+ (id)getBackupSelectionPath;
+ (id)getBackupTmpPath;
+ (unsigned long long)getFileSizeOfBackupPath;
+ (unsigned long long)getFreeDiskSpace;
+ (id)getLastBackupComputerName;
+ (id)getProgress;
+ (id)getRecoverFileBufferPathWithDataId:(id)arg1;
+ (id)getRecoverFilePathWithDataId:(id)arg1;
+ (id)getRecoverFileTmpPathWithDataId:(id)arg1;
+ (id)getRecoverReportPath;
+ (id)getRelatedMemoryKV;
+ (_Bool)getStateOfMigrated;
+ (_Bool)hasSelection;
+ (id)loadSelection;
+ (void)resetRecoverInfo;
+ (void)resetStateOfMigrated;
+ (_Bool)saveSelection:(id)arg1;
+ (void)setLastBackupComputerName:(id)arg1;
+ (void)setStateOfMigrated;
+ (void)syncClearBackupPath;
+ (void)syncClearBackupTmpData;
+ (void)syncClearBufferData;
+ (void)syncDeleteMsgListArray:(id)arg1;
+ (void)writeProgressCurrent:(unsigned long long)arg1 totalCount:(unsigned long long)arg2;
+ (void)writeRecoverDataBeignInfo;
+ (void)writeRecoverDataWaitInfo;
+ (void)writeRecoverTransferBeginInfo;

@end

