//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWindowViewController.h"

#import "IBackupExt.h"
#import "ILinkEventExt.h"
#import "MMLoadSessionExt.h"
#import "UIAlertViewDelegate.h"
#import "WXGBackupSessionViewControllerDelegate.h"

@class CTRichTextView, MMUILabel, NSString, UIButton, UIImageView, UIScrollView, UIView, WXGDotDotDotLabel;

@interface WXGBackupEntryViewController : MMWindowViewController <WXGBackupSessionViewControllerDelegate, IBackupExt, MMLoadSessionExt, UIAlertViewDelegate, ILinkEventExt>
{
    UIScrollView *m_scrollView;
    UIView *m_backgroundView;
    UIButton *m_leftTopCornerButton;
    UIImageView *m_iconImageView;
    NSString *m_lastIconName;
    MMUILabel *m_tipsLabel;
    MMUILabel *m_smallTipsLabel;
    MMUILabel *m_titleInGBPLable;
    WXGDotDotDotLabel *m_dotDotDotLabel;
    UIView *m_barLine;
    MMUILabel *m_wifiTipLabel;
    CTRichTextView *m_helpTipsLabel;
    UIButton *m_greenButton;
    UIButton *m_greyButton;
    unsigned long long m_notifyCode;
    _Bool m_bBackup;
    _Bool m_bLoadDataFinish;
    _Bool m_bStartBackup;
    _Bool m_bStartRecoverTransfer;
    _Bool m_bStartRecover;
    _Bool m_bSelectAllData;
    unsigned long long m_currentSessionCount;
    unsigned long long m_totalSessionCount;
    _Bool m_bCanShowDisconnect;
    unsigned long long m_currentShowAlertViewTag;
    NSString *m_speedString;
    _Bool m_bRecoverError;
    id <WXGBackupEntryViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)addBlurEffectForView;
- (void)addGreenButton;
- (void)addGreyButton;
- (void)addIconImageView;
- (void)addLeftCornerButton;
- (void)addLine;
- (void)addSmallTipsLabel;
- (void)addTipsLabel;
- (void)addTitleInGreenButtonPosition;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
@property(nonatomic) __weak id <WXGBackupEntryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)onAlertNowShouldRecoverData;
- (void)onAlertShowEnergyIsNotEnough;
- (void)onAlertShowMigratedCostTime;
- (void)onAlertShowNoSession;
- (void)onBackupAlertCode:(unsigned long long)arg1;
- (void)onBackupAllSession;
- (void)onBackupNotifyCode:(unsigned long long)arg1;
- (void)onBackupTransferSpeed:(float)arg1;
- (void)onBeginImport;
- (void)onBeginRecover;
- (void)onCancelBackup;
- (void)onCancelRecover;
- (void)onCancelRecoverTransfer;
- (void)onCancelSelectSession;
- (void)onCancelView;
- (void)onCloseViewAndCancelView;
- (void)onDone;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onLoadDataFinished;
- (void)onMinimizeView;
- (void)onProgressCurrentSession:(unsigned long long)arg1 totalSession:(unsigned long long)arg2;
- (void)onSelectSession:(id)arg1;
- (void)onShowSelectSessionViewController;
- (void)onStopRecover;
- (void)onUserCancelView;
- (_Bool)p_checkBatteryEnough;
- (_Bool)p_checkSessionData;
- (void)setupView;
- (void)startBackup;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

